### ISSUE TITLE
Extend API

### ISSUE THREAD

**Issue by suresttexas00** [suresttexas00/minecraft-wrapper#100]
In the player api, there are methods for, say getclient, which then allow access into wrapper's underlying client.py code.  Per our recent discussioin under [revisiting function names](https://github.com/suresttexas00/minecraft-wrapper/issues/97#issuecomment-211714772), there should be a standard api and wrapper's internal client.py methods should not be handled by the plugin dev.

These need an API:
- player.getClient()
- Minecraft.getServer()

**Comment by JasonBristol** [comment]
This is a very brief view of what should be an overall API extension/refactor
