### ISSUE TITLE
configure_logger() - logger variable not used?

### ISSUE THREAD

**Issue by suresttexas00** [suresttexas00/minecraft-wrapper#102]
In log.py, pycharm complains (i.e., i could just have pycharm not configured properly for this project) that local variable `logger` is not used.  I don't see logger passed to the function and it does not seem to get returned...

Is this an error, staging for future functionality, or have I misunderstood something?

```
def configure_logger():
    setCustomLevels()
    loadConfig()

    logger = logging.getLogger()
```

**Comment by JasonBristol** [comment]
This is to initialize the root logger, i.e. `logging.getLogger()` it was being cached as `logger` when it was being leveraged outside of the logging package. This can just read `logging.getLogger()` now since we are using native calls

**Comment by suresttexas00** [comment]
Is this also the case in class ColorFormatter?
```
    def format(self, record):
        args = record.args
        msg = record.msg
```

`args` is unused also.

**Comment by JasonBristol** [comment]
No those are access variables for our formatter and are not used now but
can be later. Honestly I would leave all three since these aren't causing
any harm, don't obscure the functionality of the Logger, follow a correct
process and may be leveraged later. No need to clean these up this
aggressively

**Comment by suresttexas00** [comment]
In that case, I will only worry about the `logger =  logging.getLogger()`, which I will just simplify for now to  `logging.getLogger()`.  Later on, if it is needed to be used or returned, we can make those changes, depending on how it will be implemented.

The only changes to log.py are logging.getlogger() and some variable renaming to avoid shadowing here:
```
def loadConfig(configfile="logging.json"):
    dictConfig(DEFAULT_CONFIG) # Load default config
    try:
        if os.path.isfile(configfile):
...
```

Also, I will be working on cleaning up some of the ambiguity with UUIDS, how (often) we poll mojang, making sure we are using MCUUID everywhere, getting rid of (or clarifying and standardizing the use of) some of the other uuid/name wrappers like getUUID and getUserName... and some various other cleanups that need to happen in the player API.  I'll pull all that back by this weekend at the lastest.  The modules I will probably be touching for sure are:
core.wrapper
core.commands
api.player

**Comment by JasonBristol** [comment]
```python
def format(self, record):
        args = record.args
        msg = record.msg

        if os.name in ("posix", "mac"): # Only style on *nix since windows doesn't support ANSI
            if record.levelno == logging.INFO:
                info_style = termcolors.make_style(fg="green")
                msg = info_style(msg)
            elif record.levelno == logging.DEBUG:
                debug_style = termcolors.make_style(fg="cyan")
                msg = debug_style(msg)
            elif record.levelno == logging.WARNING:
                warn_style = termcolors.make_style(fg="yellow", opts=("bold",))
                msg = warn_style(msg)
            elif record.levelno == logging.ERROR:
                error_style = termcolors.make_style(fg="red", opts=("bold",))
                msg = error_style(msg)
            elif record.levelno == logging.CRITICAL:
                crit_style = termcolors.make_style(fg="black", bg="red", opts=("bold",))
                msg = crit_style(msg)
            elif record.levelno == logging.TRACE:
                trace_style  = termcolors.make_style(fg="black", bg="white")
                msg = trace_style(msg)

        record.msg = msg

        return super(ColorFormatter, self).format(record)
```

msg and args are indeed used, take a closer look at this:

`msg = warn_style(msg)`

I assume your lint editor is throwing a warning because msg is not used in ALL cases, only when the os is linux or mac.

Touching this will certainly causes issues

**Comment by suresttexas00** [comment]
NOt msg... args

**Comment by suresttexas00** [comment]
The editor cannot find args being used

**Comment by suresttexas00** [comment]
As I said elsewhere, I am leaving this one alone anyway in case you wanted to add the functionality later...
