### ISSUE TITLE
Refocusing development

### ISSUE THREAD

**Issue by JasonBristol** [suresttexas00/minecraft-wrapper#103]
I will be slowing down development against Ben's wrapper, including this branch. Instead all my effort will be focused on a wrapper of my own design. 

This decision was made for a few reasons:

 - This project does not seem poised to make any fundamental changes to the way the product works, and is content with the status quo. That is **okay** but does not meet the requirements I need for my own use case.
 - Too much of Ben's wrapper needs to be refactored to justify the effort
 - Conflicting goals
 - Ben's proprietary license
 - Ben's lack of interest in the project
 - Low visibility in a forked state stifles development and community involvement
 - Development of this branch seems too focused on specific use cases and not on the general community

Slated features for my wrapper:

1. Highly modular and extensible plugin design
 - Plugins can extend plugins, plugins can extend the wrapper
2. Stable and highly extensible proxy
 - Uses a true to life socket implementation without the fuss of trying to refactor Ben's from scratch.
 - Thread safe
 - Packets are fully abstracted, instead of the odd protocol shuffling, the proxy leverages an abstract datatype packet class that will evolve to the server version. This will allow for "true" universal connect capabilities.
3. Robust event framework
4. Robust interface with the minecraft server, no more odd "api" definitions
5. Full python 2 & 3 support
6. Real package, automatically installs dependencies and tracks requirements
 - Handles updating through true to life mechanisms like pip

This is just a shortlist of features

I will pop in here from time to time so feel free to query for any issues.

This fork has been successful, and has provided value that I think can be expanded upon with a clean slate. If you are interested in getting involved, my wrapper has an Apache license and runs on python 2 and python 3 with a working prototype.

**Comment by l33tlinuxh4x0r** [comment]
Do you have a link to the prototype? I would like to test this and write plugins for it. Also do you have a link to the source? I would like to help as much as I can.

**Comment by suresttexas00** [comment]
I heartily agree.   A fresh ground up approach would really be best.  All your effort has been appreciated here and I have learned a lot from you! 

I look forward to following your progress!

You might look into barneygale's quarry https://github.com/barneygale/quarry which might make a nice backend for handing server and client connections (maybe even contribute to his project)

**Comment by suresttexas00** [comment]
Thumbs up for a system that will also abstract not just the packet names, but their contents... This is one part that will only get worse as Mojang continues to fiddle with packet formats with each protocol change.

**Comment by l33tlinuxh4x0r** [comment]
Do you have a name for your wrapper?

**Comment by barneygale** [comment]
A couple of notes about using quarry:

1. quarry is written on top of twisted. I personally think twisted is pretty good choice for writing a wrapper (including communicating with child processes in an async way, tcp/udp connections, timed events), but if it's an issue then you could have a go at making quarry support multiple backends
2. Quarry doesn't have a `Packet` class, but it's pretty easy to add new abstractions on top, e.g. replace `packet_received()` in your `{Client,Server}Protocol` subclass. This will bypass quarry's usual packet dispatching.

**Comment by JasonBristol** [comment]
I called the prototype Freyja, but I am not sure if that will stick, I have an empty repo setup and will push an alpha sometime in the near future.

Quarry looks like it will definitely be helpful, I will be running some tests with it to see if I can get a working set to try it out, @barneygale does Quarry happen to have any documentation that I could reference?

**Comment by l33tlinuxh4x0r** [comment]
Cool, I look forward to it.

**Comment by barneygale** [comment]
@JasonBristol check http://quarry.readthedocs.org/

**Comment by l33tlinuxh4x0r** [comment]
pycraft may also be helpfull. https://github.com/ammaraskar/pyCraft
