### ISSUE TITLE
xrange and py2-3 compatibility

### ISSUE THREAD

**Issue by suresttexas00** [suresttexas00/minecraft-wrapper#105]
I understand that xrange is faster in some cirumstances in py2.  But it does not exist in py3.

py3 range does what py2 xrange did (works the same with object, etc).

what is your idea for xrange-range compatibility?

**Comment by l33tlinuxh4x0r** [comment]
you could try a if python version == 2.7 use xrange else use range. You could do this be importing differnet libs for each version. Not sure if there is a python version class or not though.

**Comment by suresttexas00** [comment]
I know there are things like `six` that do wrapping and renaming and so forth to maintain cross-compatibility.. It just seems like all these items are un-needed overhead when (in our code) the 2.7 range will do the same job.  Using range will do the same job.  There is a slight performance hit in python 2.x for using range, but when you consider the extra wrapping, etc to be py3 compatible, I wonder if it is worth it.

If you decide "I want the fastest 2.x code" then using xrange is a no-brainer.  However, I think being natively 3.x compatible would be much better, even if it means a slight hit on 2.x...

@JasonBristol ?

**Comment by suresttexas00** [comment]
I worry that that `if python version == 2.7` statement would eat up the xrange efficiency gain in a tight loop...

**Comment by l33tlinuxh4x0r** [comment]
Probably so it would slow down both versions... Is there any reason for keeping python 2.x support? If so why don't we have 2 builds of the wrapper? One built for 2.7 and one for 3.5.x

**Comment by suresttexas00** [comment]
Some people don't have it (3.x) or won't use it... that is it.  Maintaining 2 versions is not something I'd like to do... It's not worth that much trouble.  Since wrapper was written heavily 2.x dependent, the challenge is just getting 3.x compatibility.  I think ultimately 3.x will be the preferred version.

**Comment by l33tlinuxh4x0r** [comment]
I agree taht 3.x will be preferred eventually. Also have you checked out my repo? I have updated the code to 3.x however it is a couple of weeks old and not everything is working. I did get it to wrap minecraft server.jar though.

**Comment by l33tlinuxh4x0r** [comment]
https://github.com/l33tlinuxh4x0r/minecraft-wrapper It builds and runs in python 3.5.1 however I don't have plugins/web/irc etc working.

**Comment by suresttexas00** [comment]
No, I have not.. did you base it on one of our experimental versions or BenBaptist's version?  I know the experimental that jason rewrote is much closer to py3 than bens...

**Comment by suresttexas00** [comment]
I have not dig into the core parts of wrapper too much, but most of the files I have been working on are pretty close to 3.4 now.. mostly just cleaning up imports... and a few common things like xrange

**Comment by l33tlinuxh4x0r** [comment]
I based it on your experimental version about a week and a half ago.

**Comment by suresttexas00** [comment]
just curious, if you are still close enough to pull my newer changes into your code base...

**Comment by suresttexas00** [comment]
I might so some comparing right quick...

**Comment by JasonBristol** [comment]
I don't t think this has any priority over other more important tasks, but
if we were to be py3 compliant we would need to go back to range()

**Comment by suresttexas00** [comment]
I may have a Py3 version ready.  As I understand, requests is available for py3, but you'll have to pip it.

I am doing a PR now for the py3 patches.

**Comment by suresttexas00** [comment]
The latest version (https://github.com/suresttexas00/minecraft-wrapper/pull/111) is "working" but not well (i.e., it runs).  

All the "obvious" bugs (syntax errors, names, usages, etc) are corrected.
Plugins will load (unless they are not PY3 workable)
if you don't supply `nogui` the server will come up in a java window.

_It does not seem to be wrapping the console._
_proxy mode appears not to work_

It also has a number of fixes for BOTH versions and shuts down cleaner.

_I have much work to do in the proxy.base. client. and server modules where uuids get confused.

**Comment by l33tlinuxh4x0r** [comment]
I would push a fixed mcserver.py if I could... However I will just post the fix here so you can add it. Line 409 needs to be changed from `self.proc = subprocess.Popen(self.args, stdout=subprocess.PIPE, stdin=subprocess.PIPE, stderr=subprocess.PIPE)` to `self.proc = subprocess.Popen(self.args, stdout=subprocess.PIPE, stderr=subprocess.PIPE, universal_newlines=True)`

**Comment by suresttexas00** [comment]
That part works now.. it will be in my next push.

**Comment by suresttexas00** [comment]
@JasonBristol I don't know enough about what you have done here with the MCUUID class...

python complains about this in python 3.4:
```
  File "/home/surest/projects/Wrapper/wrapper/core/mcuuid.py", line 11, in __init__
    super(MCUUID, self).__init__(hex, bytes, bytes_le, fields, int, version)
  File "/usr/lib/python3.4/uuid.py", line 148, in __init__
    raise ValueError('bytes is not a 16-char string')
ValueError: bytes is not a 16-char string
```

Here is the code.  I really hate this whole inconsistency between strings and bytes in PY3.  How do you fix MCUUID for python 3?

Code:
```
# -*- coding: utf-8 -*-

import uuid

class MCUUID (uuid.UUID):
    """
    This class is currently not being used, but may be beneficial in regards to
    conforming UUIDs
    """
    def __init__(self, hex=None, bytes=None, bytes_le=None, fields=None, int=None, version=None):
        super(MCUUID, self).__init__(hex, bytes, bytes_le, fields, int, version)

    @property
    def string(self):
        return str(self)
```

**Comment by JasonBristol** [comment]
All strings in Python 3 are unicode, this is not the case in Python 2 which
is why an exception is thrown. We would need `from __future__ import
unicode_literals`

**Comment by suresttexas00** [comment]
Do you have more details on that?  I used that import in both my test file and in the mcuuid.py file and I am getting the same error.

**Comment by JasonBristol** [comment]
Since the UUID class has a contructor signature that shadows builtins, and we are using inheritence to subclass that constructor, we cannot avoid shadowing in any convenient manner. I don't see any issues here if we were to ignore this.

Regarding the error you are receiving, what is the full stacktrace?

**Comment by suresttexas00** [comment]
The console wrapping now works as of #125.  mcserver or the proxy serverconnection are still not working due to byte/unicode issues... which are on hold for now.  I am just correcting things as I see them during refactors.

**Comment by suresttexas00** [comment]
back to the actual topic.. it may have been a mistake to just range everything while still using 2.7.  I have noticed serious performance drops, which may be a result of ranging over many ints.
