### ISSUE TITLE
Deprecated Libraries - track pycrypto -> pycryptodome

### ISSUE THREAD

**Issue by JasonBristol** [suresttexas00/minecraft-wrapper#11]
Lets take a look at our imports across all modules and make certain that we are leveraging the best libraries available. This does not necessarily mean we need to incorporate external dependencies -- there are a lot of great libraries baked into the python standard as of 2.7.x

If an external library is being considered, we should spin off a separate issue with the question label to ensure we collaboratively run a cost/benefit against incorporating it.

**Comment by JasonBristol** [comment]
A great example is the python [logging](https://docs.python.org/2/library/logging.html) library which elegantly allows us to manage logs as well as:

>- Loggers expose the interface that application code directly uses.
- Handlers send the log records (created by loggers) to the appropriate destination.
- Filters provide a finer grained facility for determining which log records to output.
- Formatters specify the layout of log records in the final output.

**Comment by suresttexas00** [comment]
I would really like to see better and more reliable logging.

**Comment by JasonBristol** [comment]
Adding note for md5 -> hashlib

**Comment by suresttexas00** [comment]
I got rid of these out of proxy, but I missed this one

**Comment by JasonBristol** [comment]
I think the last reference to md5 sits in ***web.py***

**Comment by suresttexas00** [comment]
I am doing a number if direct commits tonight, so make sure to pull down any changes before you start work again.  I had some problems getting this version to work.  No player could login.  Could be due to some syntax errors here and there.

**Comment by JasonBristol** [comment]
I think all of these have been cleared out, closing this

**Comment by JasonBristol** [comment]
Reopening to track pycrypto -> pycryptodome

**Comment by suresttexas00** [comment]
pycrypto is not used by wrapper.
the only cryptography module in wrapper is encryption.py (now utils.encryption), which uses Crypto!

If your recursively grep the whole repo, you only find pycryto mentioned in a core.wrapper method startProxy and in the README.md document.

**Comment by JasonBristol** [comment]
Pycrypto is crypto, pycrypto is the package name not the module name. I
recommend not closing these without confirmation from the issue owner to
avoid cases such as this

**Comment by l33tlinuxh4x0r** [comment]
yep pycryptodome is the package name for python3 and if I rememeber correctly it imports as crypto instead of Crypto.

**Comment by suresttexas00** [comment]
I'll revert those changes and see if we just need to tweak the import some for Py2-3

**Comment by suresttexas00** [comment]
So.. this is really not an actual code issue, but rather a end user setup issue (i.e. which pip install to run)?.. since it still imports as Crypto/crypto?

**Comment by l33tlinuxh4x0r** [comment]
You need to set it up differently and the case in the code matters iirc. If the case is wrong it will throw a module unable to be found and could not be loaded error.

**Comment by suresttexas00** [comment]
where in wrapper's code would it be set up "differently"

The case is a non-issue since we can (and probably should for other reasons):
```
try:
    import Crypto
except ImportError:
    import crypto
```
we are not running very complex or latest/greatest ciphers here.. very basic and limited stuff.  The items we are dealing with are not likely to ever be changed from pycrypto.

**Comment by suresttexas00** [comment]
The other cases are some windows anomalies that happen with the folder names due to the windoze filesystem being case-insensitve ( and using a "crypto' folder versus "Crypto" even on pycrypto installs).

**Comment by l33tlinuxh4x0r** [comment]
```
try:
    import Crypto
except ImportError:
    import crypto

```

Looks like it would work fine.

**Comment by suresttexas00** [comment]
that's what i wrote ..?

**Comment by suresttexas00** [comment]
As i said, I planned on doing that anyway.

**Comment by l33tlinuxh4x0r** [comment]
Sounds good.

**Comment by suresttexas00** [comment]
PyCrypto / PyCryptodome issue resolved.
