### ISSUE TITLE
PY3 Eula auto-accept is not working.

### ISSUE THREAD

**Issue by l33tlinuxh4x0r** [suresttexas00/minecraft-wrapper#112]
Just built this and when running I got the following error.
```
File "Wrapper.py/core/storage.py", line 98, in save
FileNotFoundError: [Errno 2] No such file or directory: 'wrapper-data/json/main.json'

```
I already fixed it in my version so I will fix it in the latest code and post the fix.

**Comment by l33tlinuxh4x0r** [comment]
line 78 in storage.py needs to be `os.makedirs(directory)` instead of `os.mkdir(directory)`

**Comment by l33tlinuxh4x0r** [comment]
After that error is fixed I'm now getting 

`[19:40:49] [Wrapper.py/INFO]: Stopping Minecraft server with reason: Wrapper.py crashed - please contact the server host as soon as possible
[19:40:49] [Wrapper.py/CRITICAL]: Wrapper has no server instance. Server is likely killed but could still be running, or it might be corrupted! ('NoneType' object has no attribute 'stdin')
Traceback (most recent call last):
  File "Wrapper.py/__main__.py", line 15, in <module>
    wrapper.start()
  File "Wrapper.py/core/wrapper.py", line 431, in start
    self.server.__handle_server__()
  File "Wrapper.py/core/mcserver.py", line 408, in __handle_server__
    self.reloadProperties()
  File "Wrapper.py/core/mcserver.py", line 333, in reloadProperties
    self.worldName = configfile.split("level-name=")[1].split("\n")[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

`

I'm looking to fix it now.

**Comment by l33tlinuxh4x0r** [comment]
I couldn't figure out what exactly is wrong... Something with the new world name syntax.

If you replace `self.worldName = get_args(line.split(" "), 2).replace('"', "")` with `self.worldName = get_args(line.split(" "), 5).replace('"', "")` it fixes it but then makes more errors on different lines complaining about more world name things.

**Comment by suresttexas00** [comment]
Need a copy of your server.properties file to see why that does not parse "world=whatever/n"

Are you on windows of linux?  Are you trying this on 3.x or 2.x python?

Keep in mind... the wrapper is VERY unstable and has a lot of errors that need fixed.

regarding the path.. you SHOULD have that directory in your world folder in the same directory as the server (which is where wrapper should be too).  We don't support having wrapper outside the server directory yet.

**Comment by suresttexas00** [comment]
Also, you stated you "built" it.. what does that mean exactly?  You should just be able to run the source folder directly (python "/pathtoyour/server/wrapper/"

**Comment by l33tlinuxh4x0r** [comment]
Currently using linux with python 3.5.1. I use the build script, build_script.py in the build folder. I had to modify it to get it to build. I'll post it in a second.

**Comment by l33tlinuxh4x0r** [comment]
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
import sys
import time
import json
import hashlib
import argparse
import zipfile
import subprocess

parser = argparse.ArgumentParser(
  description='Build script for Wrapper.py!', 
  epilog='Created by Jason Bristol')

parser.add_argument('source', type=str, default='.', help='the top level source directory')
parser.add_argument('branch', type=str, choices=('dev', 'stable'), default='dev', help='branch to commit changes to')
parser.add_argument('--commit',  '-c', action='store_true', help='commit changes to specified branch')
parser.add_argument('--message', '-m', type=str, default='build revision', help='commit message') 
parser.add_argument('--verbose', '-v', action='store_true', help='verbose flag')

args = parser.parse_args()

def build_wrapper(args):
  os.chdir(args.source)

  with open("build/version.json", "r") as f:
    version = json.loads(f.read())
    version["build"] += 1
    version["branch"] = args.branch
    version["release_time"] = time.time()

  with open("wrapper/core/globals.py", "w") as f:
    f.write("build=%d\nbranch='%s'" % (version["build"], args.branch))

  with open("build/version.json", "w") as f:
    f.write(json.dumps(version))

  if os.path.exists("Wrapper.py"): os.remove("Wrapper.py") # Time to start with a clean Wrapper.py!
  # subprocess.Popen("zip Wrapper.py -r . -x *~ -x *pyc", shell=True).wait()

  if args.verbose: print('Creating Archive...')
  zf = zipfile.ZipFile('Wrapper.py', mode='w')
  try:
    if args.verbose: print('Adding Files...')
    for root, dirs, files in os.walk("wrapper"):
      for f in files:
        path = os.path.join(root, f)
        if args.verbose: print('Archiving %s...' % path)
        zf.write(path, arcname=path[7:])
  finally:
    if args.verbose: print('Closing Archive...')
    zf.close()

  with open("Wrapper.py", "rb") as f:
    content = f.read()

  with open("Wrapper.py.md5", "w") as f:
    f.write(hashlib.md5(content).hexdigest())

  if args.commit: # Mainly just for me (benbaptist), since most people will probably want to build locally without committing to anything
    subprocess.Popen("git add --update :/", shell=True).wait()
    subprocess.Popen("git commit -m 'Build %s %d | %s'" % (args.branch, version["build"], args.message), shell=True).wait()
    subprocess.Popen("git push", shell=True).wait()
  print("Built version %d (%s build)" % (version["build"], args.branch))

try:    build_wrapper(args)
except: print("\n{}: {}\n".format("Unexpected error", sys.exc_info()[1]))
```

**Comment by l33tlinuxh4x0r** [comment]
It creates a Wrapper.py file instead of using just the source files... You can run just one file. Anyways here is my server.properties. 
```
#Minecraft server properties
#Sun May 08 19:40:48 UTC 2016
```

I see that the elua isn't accepted... That might be the problem... Before the server would auto accept the EULA give me a sec... I might have a fix.

**Comment by suresttexas00** [comment]
it should accept it for you.   

Until the bugs are ironed out.. I suggest running the source directly.

**Comment by l33tlinuxh4x0r** [comment]
I just like running a "built" version so as not to used cached files that python creates while funning the source directly. But either way work pretty much the same.

**Comment by suresttexas00** [comment]
It might now "quite" work the same.  Also, we are not supposed to be bumping version and build numbers  at this time. 

I will make my last push for now.  I can tell you one set of hurdles will be these kinds of errors:
```
[21:52:51] [Wrapper.py/ERROR]: Proxy could not poll the Minecraft server - are you sure that the ports are configured properly? (Can't convert 'bytes' object to str implicitly)
Traceback (most recent call last):
  File "/home/surest/server/wrapper/proxy/base.py", line 47, in host
    self.pollServer()
  File "/home/surest/server/wrapper/proxy/base.py", line 95, in pollServer
    packet.send(0x00, "varint|string|ushort|varint", (5, "localhost", self.wrapper.config["Proxy"]["server-port"], 1))
  File "/home/surest/server/wrapper/proxy/packet.py", line 192, in send
    result += self.send_varInt(pkid)
TypeError: Can't convert 'bytes' object to str implicitly
```

You're free to continue to you work on this, just please don't send in a huge update where I can't see individual changes... create separate commits.  Also, please use Git and not manual file pastes...

I'm going to have very little time over the next week due to work commitments, so It will be slow going on my end.

**Comment by l33tlinuxh4x0r** [comment]
Ok, I got it to run... Just had to manually accept the ELUA and delete the server.properties file. However the server isn't wrapping console but I see that you aded my fix to the next push as referenced https://github.com/suresttexas00/minecraft-wrapper/issues/105#issuecomment-217761221

**Comment by suresttexas00** [comment]
It worked on mine (I can at least see the server output in console now).

**Comment by l33tlinuxh4x0r** [comment]
Ok, I'll have to learn how to use git, I only know how to clone from the command line never pushed anything LOL

**Comment by l33tlinuxh4x0r** [comment]
Just saw the clean-3 branch I will test it...

**Comment by suresttexas00** [comment]
try this:
(and take notes)
https://try.github.io/levels/1/challenges/1

I will merge the last commit into experimental.

**Comment by suresttexas00** [comment]
Can you get a copy of that server properties file?

**Comment by l33tlinuxh4x0r** [comment]
I'm about to run the latest... I will post my server properties file if I have another issue.

**Comment by suresttexas00** [comment]
Where did that code above come from.. I dont recognize it. ??

```
I couldn't figure out what exactly is wrong... Something with the new world name syntax.

If you replace self.worldName = get_args(line.split(" "), 2).replace('"', "") with self.worldName = get_args(line.split(" "), 5).replace('"', "") it fixes it but then makes more errors on different lines complaining about more world name things.
```

**Comment by l33tlinuxh4x0r** [comment]
It isn't broken... I just needed to accept the elua and then it didn't need a fix

**Comment by suresttexas00** [comment]
That's still an issue... JasonBristol made that to auto- accept the eula... I am sure it is another instance of getting text and binary mixed up because Py2 used them interchangeably (text was just binary)

**Comment by l33tlinuxh4x0r** [comment]
```
def acceptEula(self):
        if os.path.isfile("eula.txt"):
            with open("eula.txt", "r") as f:
                eula = f.read()
                
            if "false" in eula:
                with open("eula.txt", "w") as f:
                    f.write(eula.replace("false", "true"))
```

should accept the elua

**Comment by suresttexas00** [comment]
I am misunderstanding... is this "the fix" or "what should have worked"?

also, I need to add back the `stdin=subprocess.PIPE,` your code took out (removed the ability to type commands to wrapper).

**Comment by l33tlinuxh4x0r** [comment]
stdin=subprocess.PIPE cannot be used with Universal new lines... It is automatically enabled... Check the python docs on popen.

**Comment by l33tlinuxh4x0r** [comment]
It might break 2.7 but it is correct for 3

**Comment by suresttexas00** [comment]
so this is corrected code?  What module again?

**Comment by suresttexas00** [comment]
You should consider installing 2.7... that way you can test changes against both versions.

**Comment by l33tlinuxh4x0r** [comment]
I cannot push to the repo... it says permission denied... However there is a bug fix that I just found...

line 78 of storage.py should be `os.makedirs(directory)` instead of `os.mkdir(directory)`

**Comment by suresttexas00** [comment]
what is that an error?  It works on 3.4 at least...  what is the error?

**Comment by l33tlinuxh4x0r** [comment]
try deleting your wrapper-data directory and trying again... It cannot make the directory the makedirs is like mkdir -p on linux.

 ```
File "/home/l33tlinuxh4x0r/MCWW/mctest/wrapper/core/storage.py", line 98, in save
    with open("%s/%s.json" % (self.root, self.name), "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'wrapper-data/json/main.json'


```

**Comment by l33tlinuxh4x0r** [comment]
Also this fixes the bug about accepting the ELUA.

**Comment by suresttexas00** [comment]
you must 
1) using your fork...
2) clone your branch
3) make changes, add, commit, and push them back to github
4) in guthub, make a pull request with my experimental as the base and yours as the head.

**Comment by suresttexas00** [comment]
yep, i see now... there have been alot of changes to storage... 

I'll go through all the code and upgrade these mkdir instances to makedirs

**Comment by suresttexas00** [comment]
OK... I am going to be doing a lot of work in the proxy modules.. avoid any changes there.. if you do want something changed, let me know where and I'll include it.

**Comment by suresttexas00** [comment]
Looked into this more.. if you change anything to makedirs, use, `os.makedirs(directory, exist_ok=True)` so an error is not thrown if some part of the directory already exists.
http://stackoverflow.com/questions/13819496/what-is-different-between-makedirs-and-mkdir-of-os

**Comment by JasonBristol** [comment]
A big FYI for any python 3 support issues, all string, read _ALL_, are by default unicode. This is also enforced at the pipe level, i.e. `stdin.write`. I have already worked and resolved all of these kind of issues in some of the experimental py3 work I was doing with Wrapper, but `storage.py` and `mcserver.py` were the two that definitely stood out as being python 3 non-compliant. 

Keep in mind this also causes issues with file paths since right now they are not unicode within wrapper.
