### ISSUE TITLE
Inspect Potential Idle and Duplicate Threads

### ISSUE THREAD

**Issue by JasonBristol** [suresttexas00/minecraft-wrapper#12]
Wrapper does not follow safe threading practices and is prone to performance issues and high CPU usage. 

All of our threads are suspect and need to be investigated/refactored.

**Comment by JasonBristol** [comment]
On hold until #8 is completed

**Comment by JasonBristol** [comment]
This may not be as bad as I initially thought. After inspecting many of our threads, all are daemonized meaning once our main thread exits, it takes with it all child threads. So instead of our threads being "unsafe" I am switching gears to inspect our thread performance.

While our threads may be safe, I think many are being allowed to linger during the lifespan of a single wrapper instance. Even more concerning I think multiple threads are being spawned for the same task as objects are being reinitialized in various areas.

**Comment by suresttexas00** [comment]
`While our threads may be safe, I think many are being allowed to linger during the lifespan of a single wrapper instance.` - Yep, seen lots of this during the past two weeks of refactoring.

**Comment by suresttexas00** [comment]
This is essentially complete.  Can go to an informal status
