### ISSUE TITLE
Howto Build?

### ISSUE THREAD

**Issue by hunter688** [suresttexas00/minecraft-wrapper#127]
Please add to documentation howto build wrapper from sourcecode.

**Comment by suresttexas00** [comment]
You don't need to build it.  Just place the contents of the /wrapper source folder into the same folder with your minecraft world, then run it from a shell with `python "/pathtoyourserver/server/wrapper/"` 

We won't be doing an actual "build" (i.e., creating a single wrapper.py python file) on this fork... 

Python lets you run the source code directly.

**Comment by suresttexas00** [comment]
Here is the reason why I am not doing wrapper.py builds at this time:
https://github.com/benbaptist/minecraft-wrapper/wiki/Contributors-Guidelines
