### ISSUE TITLE
Cleanup Comments

### ISSUE THREAD

**Issue by JasonBristol** [suresttexas00/minecraft-wrapper#15]
We should review and cleanup code comments throughout wrapper, this will help improve readability. Many comments provide value in regards to future modifications, we should bring these out at a higher level in github as either issues with the feature/enhancement label, or note them in our roadmap.

**Comment by JasonBristol** [comment]
Example:

```python
@staticmethod
    def formatUUID(playeruuid):
        """
        Takes player's uuid with no dashes and returns it with the dashes
        :param playeruuid: string of player uuid with no dashes (such as you might get back from Mojang)
        :return: string hex format "8-4-4-4-12"
        """
        return uuid.UUID(bytes=playeruuid.decode("hex"))
```

This is a great way to document our functions, I would include this as a part of cleaning up comments

**Comment by suresttexas00** [comment]
agreed 100%.

**Comment by JasonBristol** [comment]
On hold until the conclusion of Staged Release 1

**Comment by suresttexas00** [comment]
A general case of agreement has been reached.. close thread.
