### ISSUE TITLE
Unable to launch

### ISSUE THREAD

**Issue by pingpong1109** [suresttexas00/minecraft-wrapper#183]
I am getting this error

` python __main__.py

   [21:03:47] [root/INFO]: Logging configuration file (logging.json) located and loaded, logging configuration set!
Traceback (most recent call last):
  File "__main__.py", line 10, in <module>
    wrapper = Wrapper()
  File "/home/pingpong1109/wrapperinteractiveuhc/wrapper/core/wrapper.py", line 70, in __init__
    self.storage = Storage("main", encoding=self.encoding)
  File "/home/pingpong1109/wrapperinteractiveuhc/wrapper/core/storage.py", line 21, in __init__
    self.load()
  File "/home/pingpong1109/wrapperinteractiveuhc/wrapper/core/storage.py", line 73, in load
    self.mkdir(self.root)
  File "/home/pingpong1109/wrapperinteractiveuhc/wrapper/core/storage.py", line 70, in mkdir
    self.log.warning("Could not create directory '%s' \n(%s)", dirpath, e)
AttributeError: Storage instance has no attribute 'log'
Exception AttributeError: "Storage instance has no attribute 'log'" in <bound method Storage.__del__ of <core.storage.Storage instance at 0x7fe5503becb0>> ignored`

It is really weird and Google doesn't show anything much. I believe this is a bug with the code itself.

**Comment by suresttexas00** [comment]
I have no idea why log would not be valid attribute since the logger was loaded.  Make sure you are using Py2 or we are just chasing our tails.
change that line to :+1: 
```
self.log.warning("Could not create directory '%s' \n(%s)" % (dirpath, e))
```
I need to see what that prints.

**Comment by suresttexas00** [comment]
Also... what command are you using to start wrapper?

I am working on an update this week to iron out a few bugs... You may want to try then. (i'll let you know).  The current code ought to be in a pretty good state though (branch experimental)

**Comment by suresttexas00** [comment]
I have duplicated your error with a fresh setup using the same wrapperinteractiveuhc folder name in my home directory.. so I'll get this tracked down and fixed.

**Comment by pingpong1109** [comment]
ok thank you.

Also I was using `python __main__.py` as a command

**Comment by suresttexas00** [comment]
Oh, yes, dont do that either.  Either run the Wrapper.py or run the source directory:

`python "/home/pingpong1109/wrapperinteractiveuhc/wrapper"`
or
`python "/home/pingpong1109/wrapperinteractiveuhc/Wrapper.py"`

**Comment by suresttexas00** [comment]
I do have it fixed, but I need to fix it completely so that it handles a world not being generated yet either.  I should be done by EOD.

**Comment by pingpong1109** [comment]
Ah ok thanks again

**Comment by suresttexas00** [comment]
#187
