### ISSUE TITLE
Build out MCUUID Class

### ISSUE THREAD

**Issue by JasonBristol** [suresttexas00/minecraft-wrapper#20]
We have a somewhat significant UUID problem where we leverage the uuid library to coerce uuid strings into RFC 4122 compliant UUIDs. The problem is that we are really bad at knowing when these are objects or strings due to our naming conventions.

I propose we subclass the UUID object and create a string property that will clearly delineate when a UUID is a string or an object. We should also take the opportunity to refactor our variable names to represent what type they should represent, i.e. `uuid` vs `uuidObj` etc.

```python
import mcuuid

uuidObj = mcuuid.MCUUID(uuid)
uuidStr = uuidObj.string
```

A staged version of this class is bundled into #18

**Comment by suresttexas00** [comment]
Agreed very strongly.. Remember thought to keep the external facing methods (player object) the same... which should not be a problem since they were inconsistently returned before (many times our plugins had to str() a UUID).

**Comment by JasonBristol** [comment]
Yah my hope for this is to handle all interactions with UUIDs, this way we are not worried about if a UUID is a string or an object, just that it is an MCUUID

**Comment by JasonBristol** [comment]
Patch 2 will include UUIDs normalized to MCUUIDs

**Comment by JasonBristol** [comment]
This was pushed in #33
