### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by JasonBristol** [suresttexas00/minecraft-wrapper#24]
We should add Python 3 support and start leveraging the `__future__` module throughout wrapper, this should allow users to execute wrapper on a Python 3 environment until we are ready to go full Python 3 if that is a desired.

**Comment by JasonBristol** [comment]
On Hold until code cleanup and refactor is completed

**Comment by JasonBristol** [comment]
Moving to FP 2

**Comment by l33tlinuxh4x0r** [comment]
Porting to python3 is fairly simple... I have the current code mostly ported. Also FYI Crypto is superseded by pycryptodome. On windows with python 3.5.1 you can install it with the command "pip install pycryptodome" Hope that this helps.

**Comment by JasonBristol** [comment]
Ahh interesting, did not know that pycrypto is no longer maintained. I will reopen #11 to keep tabs on that

**Comment by suresttexas00** [comment]
@l33tlinuxh4x0r just be aware that the benbaptist branches do not have any of our changes yet.  The code base is almost completely different from what we started with in the benbaptist/development branch.  We are making all changes on my "experimental" branch at present.

**Comment by l33tlinuxh4x0r** [comment]
Thanks, I realize this... I have been using your code. I realize that the benbaptist code is about a year old. I grabbed your experimental branch becuase it is the newest. If you like I could zip up my code and make a link. I did however notice that the Web management is broken... I'm currently trying to get that working.

**Comment by l33tlinuxh4x0r** [comment]
I have forked this project and uploaded my version of the code. Note: there are several bugs currently. Plugins and server commands do not currently work, nor does irc, proxy, web. I am working on fixing these issues.

**Comment by suresttexas00** [comment]
Normally I would say to do a pull request... However, This may be a better idea to simply continue to implement py3 module by module as we continue to rewrite wrapper.

One other thing.. we are not doing builds on our branch at this time... I think everything in the experimental branches /build is a work in progress presently.

also, I am curious...  presently, many py2 users run wrapper using the wrapper.py file builds. said file is a archive of the source wrapper folder that is renamed with a .py extension... py2 recognizes it as a python folder, however (at least when I last tried in windows) Py3 did not recognize it...

**Comment by suresttexas00** [comment]
https://github.com/benbaptist/minecraft-wrapper/wiki/Contributors-Guidelines

**Comment by l33tlinuxh4x0r** [comment]
It works on windows. You just need to update the python files in the code to python 3 and it will run the Wrapper.py archive. Which by the way is a really cool way to do things instead of distributing a bunch of scripts you distribute one file!

**Comment by JasonBristol** [comment]
It may be convenient, but it is not the best way to package python code. You will never see python file packaged like that in the open. Ideally one should leverage setuptools to build a real python package (via `setup.py`) that allows wrapper to be added to the python path and referenced via `wrapper.core.base` vs `core.base`, etc)

I already have a working version of this in py2/py3 in my dev environment.

**Comment by suresttexas00** [comment]
That was how Ben originally developed this (and as it is currently on his branch).  I never used it because I never really thought it was any better than just running the source directory.  I think having it as a true py package is truly the future of wrapper.

**Comment by l33tlinuxh4x0r** [comment]
Personally I would convert it to binary. Use a program like py2exe on windows (not sure about linux as I always have python installed anyway) so that users don't have to install Python if they don't need it for anything else.

**Comment by suresttexas00** [comment]
Well, here is a little trivia for ya... __pycrypto is not used by wrapper!__
the only cryptography module in wrapper is encryption.py (now utils.encryption), which uses Crypto!

If your recursively grep the whole repo, you only find pycryto mentioned in a core.wrapper method startProxy and in the README.md document.

**Comment by l33tlinuxh4x0r** [comment]
oh yeah... Crypto is the py3 version and md5 was is now part of hashlib.
```
from Crypto.PublicKey import RSA
from Crypto import Random
from Crypto.Cipher import AES, DES
from hashlib import md5
```

**Comment by suresttexas00** [comment]
I learned something today.  A very good video to watch:
https://www.youtube.com/watch?v=OSGv2VnC0go&feature=youtu.be

I see we have been abusing range/xrange regularly in wrapper.
Here's an example where we create a range loop just to "do something" x number of times (x is not even used!):

```
for x in range(entitycount):
                    eid = self.packet.readpkt(parser)[0]
                    self.wrapper.javaserver.world.delentities.append(eid)
```

```
                while entitycount: 
                    eid = self.packet.readpkt(parser)[0]
                    self.wrapper.javaserver.world.delentities.append(eid)
                    entitycount -= 1
```

Another abusive example:
```
for i in xrange(0, len(rx)):
                    if "account.mojang.com" in rx[i]:
```
which should be:
```
                for entry in rx:
                    if "account.mojang.com" in entry:
```

**Comment by suresttexas00** [comment]
Maintaining this as https://github.com/benbaptist/minecraft-wrapper/issues/301
