### ISSUE TITLE
Pull Wrapper Update URL into Config

### ISSUE THREAD

**Issue by JasonBristol** [suresttexas00/minecraft-wrapper#25]
This will allow users to auto update their wrappers from whatever repository they want to, this is good for forks.

```
[Advanced]
base-branch = <url>
dev-branch = <url>
```

This will require changes to our update logic since currently we check against the `build/` folder values in `version.json` etc. We should instead leverage some of the elements mentioned in #59

**Comment by suresttexas00** [comment]
I have mostly left what progress you made here along.  Did some small debugging along the way to the 'build_script.py', but I really am not sure where we are with this.  We appear to still be fully implemented into the existing paradigm (hopefully that is not in some broken intermediate state between the two)?

**Comment by suresttexas00** [comment]
Done.  Will be in build 136.
```
    "General": {
        "auto-restart": True,
        "auto-update-branch": None,  # Point to "dev" or "stable", as desired
        "auto-update-dev-build": "deprecated",  # no separate item for wrapper/dev-build.
        "auto-update-wrapper": False,  # If True, an "auto-update-branch" must be specified.
        # You can point these to another branch, if desired.
        "stable-branch": "https://raw.githubusercontent.com/benbaptist/minecraft-wrapper/master/build/version.json",
        "dev-branch": "https://raw.githubusercontent.com/benbaptist/minecraft-wrapper/development/build/version.json",
        # You will need to update this to your particular server start command line.
        "command": "java -jar minecraft_server.jar nogui",
```
