### ISSUE TITLE
Bad File Descriptor & Zero Length Packet in Packet.py during player disconnect

### ISSUE THREAD

**Issue by JasonBristol** [suresttexas00/minecraft-wrapper#30]
These are issues that have existed for awhile in Wrapper and had limited visibility pre #6. We should investigate these issues and determine if these are safe to suppress. 

```python
Traceback (most recent call last):
  File "wrapper/proxy/server.py", line 566, in handle
    pkid, original = self.packet.grabPacket()
  File "wrapper/proxy/packet.py", line 67, in grabPacket
    dataLength = self.unpack_varInt()
  File "wrapper/proxy/packet.py", line 94, in unpack_varInt
    val = struct.unpack('B', self.recv(1))[0]
  File "wrapper/proxy/packet.py", line 376, in recv
    d = self.socket.recv(length)
  File "/usr/lib/python2.7/socket.py", line 170, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor
```

```python
Traceback (most recent call last):
  File "wrapper/proxy/client.py", line 633, in handle
    pkid, original = self.packet.grabPacket()
  File "wrapper/proxy/packet.py", line 61, in grabPacket
    length = self.unpack_varInt()
  File "wrapper/proxy/packet.py", line 94, in unpack_varInt
    val = struct.unpack('B', self.recv(1))[0]
  File "wrapper/proxy/packet.py", line 378, in recv
    raise EOFError("Packet was zero length, disconnecting")
EOFError: Packet was zero length, disconnecting
```

Caused by:

***packet.py***
```python
def recv(self, length):
        if length > 200:
            d = ""
            while len(d) < length:
                m = length - len(d)
                if m > 5000:
                    m = 5000
                d += self.socket.recv(m)
        else:  # $ find out why next line sometimes errors out bad file descriptor
            d = self.socket.recv(length)
            if len(d) == 0:
                raise EOFError("Packet was zero length, disconnecting")
      # while length > len(d):
      #     print "Need %d more" % length - len(d)
      #     d += self.socket.recv(length - len(d))
      #     if not length == len(d):
      #         print "ACTUAL PACKET NOT LONG %d %d" % (length, len(d))
      #         print "Read more: %d" % len(self.socket.recv(1024))
      #       raise EOFError("Actual length of packet was not as long as expected!")
        if self.recvCipher is None:
            return d
        return self.recvCipher.decrypt(d)
```

```python
def grabPacket(self):
        length = self.unpack_varInt()
        # if length == 0: return None
        # if length > 256:
        #     print "Length: %d" % length
        dataLength = 0
        if self.compressThreshold != -1:
            dataLength = self.unpack_varInt()
            length = length - len(self.pack_varInt(dataLength))
        # $ part of the bad file descriptor rabbit trail
        payload = self.recv(length)
        if dataLength > 0:
            payload = zlib.decompress(payload)
        self.buffer = StringIO.StringIO(payload)
        pkid = self.read_varInt()
        return (pkid, payload)
```

**Comment by suresttexas00** [comment]
I have always found these errors confusing.  They are caused when a client has disconnected, but somehow the client has sent the packets (just before disconnecting).  A very old error.  I think one the other problems are resolved, we should focus on finding out why it exists... maybe the wrapper client should be ended sooner in the proxy instance or something, I dunno...

**Comment by JasonBristol** [comment]
Agreed, this is an interesting issue since it sits at a low level within our socket implementation. Not coming from a networking background I will need to do some reading to see if I can identify the root cause. From first glance I know we can definitely cleanup our socket implementation as we never really close any of them safely. This may be related to the socket still live and listening after the user has basically disconnected so it hard crashes at zero length.

**Comment by suresttexas00** [comment]
Yes, I think that is what happens.  I am going to have to look at this further too.  Here is an interesting line of investigation... If you reactivate the commented out lines (lining the tabs back up with the 'if pkid ==' parsing, you will find that the player object is sometimes already defunct.. yet why is the program running client parsing?  Hmmmm...?

Lines 394-403 of proxy/client.py...
```
            except Exception as e:
                self.log.exception("Formulating CHAT_MESSAGE failed (%s)", e)

            # if self.getPlayerObject().hasGroup("test"):
            #     pass

        if pkid == self.pktSB.PLAYER_POSITION: # player position
            data = self.read("double:x|double:y|double:z|bool:on_ground")
            self.position = (data["x"], data["y"], data["z"])
            self.log.trace("(PROXY CLIENT) -> Parsed PLAYER_POSITION packet:\n%s", data)
```

**Comment by suresttexas00** [comment]
These are also being caused by player pings from the client server list.

**Comment by JasonBristol** [comment]
All packets have a varint length prefix that should allow us to modify `recv` to perform I/O blocking until the entire length is received, then automatically close the socket. Will explore this after we get bugs squashed

**Comment by JasonBristol** [comment]
Minecraft packets are prefixed with a varint length, this is following the TCP standard since you may not receive all of the data in one packet, but across many. Therefore via `recv` we can pass in the packet length to trigger a blocking I/O -- this means that the socket will wait until it receives all of the data specified by length, i.e. `recv(length)`

In our `grabPacket` function it appears that Ben has done that, and has also signaled that this is where these issues begin.

```python
def grabPacket(self):
    length = self.unpack_varInt()
    # if length == 0: return None
    # if length > 256:
    #     print "Length: %d" % length
    dataLength = 0
    if self.compressThreshold != -1:
        dataLength = self.unpack_varInt()
        length = length - len(self.pack_varInt(dataLength))
    # $ part of the bad file descriptor rabbit trail
    payload = self.recv(length)
    if dataLength > 0:
        payload = zlib.decompress(payload)
    self.buffer = StringIO.StringIO(payload)
    pkid = self.read_varInt()
    return (pkid, payload)
```

Lets look at our `recv()` function which is a wrapper to `socket.recv()` and allows us to define our own protocol:

```python
def recv(self, length):
        if length > 200:
            d = ""
            while len(d) < length:
                m = length - len(d)
                if m > 5000:
                    m = 5000
                d += self.socket.recv(m)
        else:  # $ find out why next line sometimes errors out bad file descriptor
            d = self.socket.recv(length)
            if len(d) == 0:
                raise EOFError("Packet was zero length, disconnecting")
      # while length > len(d):
      #     print "Need %d more" % length - len(d)
      #     d += self.socket.recv(length - len(d))
      #     if not length == len(d):
      #         print "ACTUAL PACKET NOT LONG %d %d" % (length, len(d))
      #         print "Read more: %d" % len(self.socket.recv(1024))
      #       raise EOFError("Actual length of packet was not as long as expected!")
        if self.recvCipher is None:
            return d
        return self.recvCipher.decrypt(d)
```

It looks like Ben is trying to wait for the entire length of the packet manually, but I am under the impression that `socket.recv` does this automatically.

**Comment by suresttexas00** [comment]
actually, I think i put that in there based on console error tracebacks

**Comment by JasonBristol** [comment]
Are we closing the server listening socket before closing the client socket?

**Comment by JasonBristol** [comment]
***server.py***

```python
def close(self, reason="Disconnected", kill_client=True):
    self.log.debug("Last packet IDs (Server -> Client) of player %s before disconnection: \n%s", self.username, self.lastPacketIDs)
    self.abort = True
    self.packet = None
    try:
        self.socket.close()
    except Exception as e:
        pass

    if not self.client.isLocal and kill_client:  # Ben's cross-server hack
        self.client.isLocal = True
        self.client.send(self.pktCB.CHANGE_GAME_STATE, "ubyte|float", (1, 0))  # "end raining"
        self.client.send(self.pktCB.CHAT_MESSAGE, "string|byte", ("{text:'Disconnected from server: %s', color:red}" % reason.replace("'", "\\'"), 0))
        self.client.connect()
        return

    # I may remove this later so the client can remain connected upon server disconnection
    # self.client.send(0x02, "string|byte", (json.dumps({"text": "Disconnected from server. Reason: %s" % reason, "color": "red"}),0))
    # self.abort = True
    # self.client.connect()
    if kill_client:
        self.client.abort = True
        self.client.server = None
        self.client.close()
```

It looks like we are...

**Comment by JasonBristol** [comment]
***client.py***
```python
def close(self):
    self.abort = True
    try:
        self.socket.close()
    except Exception as e:
        self.log.exception("Could not close client socket! (%s)", e)
    if self.server:
        self.server.abort = True
        self.server.close()
    for i, client in enumerate(self.wrapper.proxy.clients):
        if client.username == self.username:
            del self.wrapper.proxy.clients[i]
```

**Comment by suresttexas00** [comment]
This is a part of the code I have mostly avoided because it is wizard of Oz stuff to me :D ...  I have pretty much ignored this part until it gets to the packet parsing part... I'm a little behind you here bceause I am still stuck at wanting to know what you want to do with #41

**Comment by JasonBristol** [comment]
Tracing this in an idea state:

1. Player disconnects from server
2. Server socket is closed
  a. Client socket is asked to close
3. Client socket closes
  a. Server socket is asked to close

This is cyclical, by the time the client is asked to close, the server has stopped listening

**Comment by suresttexas00** [comment]
that makes sense.

**Comment by JasonBristol** [comment]
Increasing priority of this since it points to some networking flaws in our socket implementation. Impact is minor, but prevalent in larger servers

**Comment by suresttexas00** [comment]
I would like to change the logging error level on this from Error to debug... while it is technically an error:
1) We know that it is largely harmless to the overall operation
2) It creates an un-manageable amount of spam to console when the focus may be another aspect of wrapper operation... 
3) Is is buggy, but known bugginess and can be seen readily with a "debug" setting the logging.json file

**Comment by JasonBristol** [comment]
In the handle function of proxy.client and proxy.server we would just need to comment out the following:

```python
except EOFError as eof:
    # This error is often erroneous, see https://github.com/suresttexas00/minecraft-wrapper/issues/30
    self.log.exception("Packet EOF (%s)", eof) # <-- this line
    self.close()
    break
except Exception as e1:
    # Bad file descriptor often occurs, see https://github.com/suresttexas00/minecraft-wrapper/issues/30
    self.log.exception("Failed to grab packet [SERVER] (%s):", e1) # <-- this line
    return
```

I would prefer to just comment them out for right now since the exception message is the same for each instance that it is caught, and we have it logged here. For the same reason the console is being spammed with these two errors, our debug stream would be spammed as well and made ineffective.

**Comment by suresttexas00** [comment]
Those are the same lines that I commented out in the development version... I did not think we wanted that to be done with the experimental branch; I thought maybe just relegating these lines to debug status would suffice.

**Comment by JasonBristol** [comment]
I uncommented this so we know the full error if any other traces were
hidden with the previous handling. No... We want this in experimental, this
is our bleeding edge branch, we do dev here, this isn't a production
branch. Don't change these to DEBUG, you will flood our debug stream and
all of our debug logging gets lost
On Apr 22, 2016 9:17 AM, "Surest Texas" <notifications@github.com> wrote:

Those are the same lines that I commented out in the development version...
I did not think we wanted that to be done with the experimental branch; I
thought maybe just relegating these lines to debug status would suffice.

—
You are receiving this because you were assigned.
Reply to this email directly or view it on GitHub
<https://github.com/suresttexas00/minecraft-wrapper/issues/30#issuecomment-213425378>

**Comment by suresttexas00** [comment]
The socket protocols do not have a "disconnect" signal to tell a connection "I am leaving now"... they simply end with no further bytes.  Unfortunately,  from what I have been reading, this is just how it is.. Anytime the socket runs out of bytes, the connection has ended.  Our code simply needs to acknowledge this and close the appropriate threads and client/server instances, including all their logs, flush threads, etc...
