### ISSUE TITLE
self.data does not resolve

### ISSUE THREAD

**Issue by suresttexas00** [suresttexas00/minecraft-wrapper#36]
Should this item be `self.plugins[index] = value` instead of `self.data[index] = value`?

```

    def __setitem__(self, index, value):
        if not type(index) == str:
            raise Exception("A string must be passed - got %s" % type(index))
        self.data[index] = value
        return self.plugins[index]
```

**Comment by JasonBristol** [comment]
Looks like it, what file was this from?

**Comment by JasonBristol** [comment]
Looks like this is in **plugins.py**, I wonder what the side effect of adding the value to `self.data` is? This should be as you said `self.plugins[index] = value`

**Comment by suresttexas00** [comment]
I will correct it in my patch

**Comment by suresttexas00** [comment]
Sorry for not telling you the module :P
