### ISSUE TITLE
Old error in commands.py

### ISSUE THREAD

**Issue by suresttexas00** [suresttexas00/minecraft-wrapper#37]
This error has been around for ever and my theory is that `command` should be in quotes: `"command"`:

Commands.py line 45:
``` self.commands[pluginID][command](payload["player"], payload["args"])```

There is no variable in the code called `command`...

**Comment by JasonBristol** [comment]
Possible resolution in #44

**Comment by suresttexas00** [comment]
The problem with this one is that I never saw any errors from it.. at least we have a log if it does happen to produce any... I think this can be closed for now.

**Comment by JasonBristol** [comment]
Yah it is interesting, I see `command` defined later, pushing up to the top causes an exception. For now I assume it is trying to access the command key of the payload. This may fade away after we complete all cleanup since command.py is definitely going to get refactored.

Closing for now
