### ISSUE TITLE
INFO vs DEBUG vs TRACE Colors for Wrapper Logging

### ISSUE THREAD

**Issue by JasonBristol** [suresttexas00/minecraft-wrapper#45]
Currently the following color scheme is used:

Vanilla Logs - White
Wrapper INFO - White
Wrapper WARN - Yellow
Wrapper ERROR - Red
Wrapper DEBUG - Cyan
Wrapper TRACE - Green

This color scheme compliments both linux and windows default shells effectively ruling out Black and Blue as possible logging colors.

Magenta is available, but appears to be buggy in windows. This can be retested to see if magenta is a viable solution for TRACE.

Assuming magenta can be leveraged, the following changes can occur:

Wrapper INFO - Green
Wrapper TRACE - Magenta

This maintains DEBUG messages appearing in Cyan. It is important to visually distinguish debug and info levels to improve debugging throughput. 

Outside of personal preference, this comes from over 10 years of real experience debugging enterprise applications where seeing a single debug statement in a sea of INFO statements is critical. We *will* want to keep these two logging levels distinguishable from each other

Leverage this issue as a discussion board.

**Comment by suresttexas00** [comment]
I agree with what you are saying, and I would like to see magenta as as valid option... but my experience with wrapper is that the distinction between server and wrapper is generally more important.  Perhaps making the wrapper's white _Italicized_ would be another option to consider.

**Comment by JasonBristol** [comment]
I am able to confirm that magenta does not currently show up under the windows powershell shell:

![image](https://cloud.githubusercontent.com/assets/3958523/14482357/eb9e216c-0109-11e6-9d1f-246b7aceb46a.png)

![image](https://cloud.githubusercontent.com/assets/3958523/14482366/fa609ac2-0109-11e6-83c7-d7d018deaf4e.png)

**Comment by JasonBristol** [comment]
This is a good idea, we do also have access to certain formatting:

`opt_dict = {'bold': '1', 'underscore': '4', 'blink': '5', 'reverse': '7', 'conceal': '8'}`

Italics is not an option, but we should be able to bold wrapper output. I can confirm that conceal, blink, and sometimes reverse do not work under windows

**Comment by JasonBristol** [comment]
Underline and bold do not appear to work in windows, this rules out any formatters. Exploring background colors for trace to bring green to INFO.

Background of yellow results in white under windows:

![image](https://cloud.githubusercontent.com/assets/3958523/14482459/f754bb46-010a-11e6-842c-e887c2b2e5e5.png)

**Comment by suresttexas00** [comment]
Too bad.. italics would have looked gooooood.

**Comment by JasonBristol** [comment]
Oddly enough now powershell won't interpret ANSI color codes... We may only be able to really offer termcolors for linux

**Comment by JasonBristol** [comment]
For now I have set TRACE to black on white and given INFO green, this should work and compliment windows/linux terminals. This should be pushed in my next commit.

For now I will close this and spin up a new issue regarding windows ANSI color code parsing
