### ISSUE TITLE
Spectator cannot pass though solid walls

### ISSUE THREAD

**Issue by suresttexas00** [suresttexas00/minecraft-wrapper#47]
These errors all sound like a uuid issue.. no console or errors to report.  Sounds like a local uuid or mojang is wrong and messing up the spectate packet.  My /van (which sends a playerlist item to remove a player) is also not causing removal from the tab list.. again, sounds like wrong uuid is being retransmitted during the client packet parsing process.

**Comment by suresttexas00** [comment]
Ill work on this tomorrow.

**Comment by JasonBristol** [comment]
You can trace the spectator packet in the `wrapper.trace.log` to see what payload it was sending

**Comment by suresttexas00** [comment]
ill turn  that on

**Comment by suresttexas00** [comment]
That does not work.  That only monitors "natural" packets from client to server, not the modded versions that get re-transmitted:

```
        if pkid == self.pktSB.SPECTATE: # Spectate - convert packet to local server UUID
            data = self.read("uuid:target_player")
            self.log.trace("(PROXY CLIENT) -> Parsed SPECTATE packet:\n%s", data)
            for client in self.proxy.clients:
                if data["target_player"].hex == client.uuid.hex:
                    self.server.send(self.pktSB.SPECTATE, "uuid", [client.serverUUID]) # Convert SPECTATE
                    return False
```

this: `self.server.send(self.pktSB.SPECTATE, "uuid", [client.serverUUID])` does not get logged.  I'll have to print it out.

**Comment by JasonBristol** [comment]
Once re-transmitted is the packet parsed by the server or the client? I do not see any server side parsing of SPECTATE packets, is this client side only?

**Comment by JasonBristol** [comment]
I can also confirm this issue on my end, spectators enter spectate mode but are unable to pass through objects, no SPECTATE packets are picked up in the trace log whihc means `pkid` never equals `self.pktSB.SPECTATE`, does this still hold true `SPECTATE = 0x1b`?

**Comment by suresttexas00** [comment]
The spectate packets are received by the wrapper proxy from the client.  They are converted/modded with the server-side (offline) uuid and then passed from proxy to the server... the "retransmitted" packet does not pass through proxy.

yes, I am also unable to detect an incoming spectate.  I verified this by adding print statements... looking at the protocol documentation, the packet itself does not even seem to mean what I thought it was. However, spectate is still 0x1b.  The error is likely somewhere else, as this packet does not set or control spectator mode as far as I can see.

**Comment by suresttexas00** [comment]
Our naming conventions in wrapper are somewhat confusing because "client" is handing server-bound traffic and server is handling client-bound traffic, the exact opposite of how protocol wiki is written.

**Comment by JasonBristol** [comment]
Lol that sounds fun, we can add correcting that to phase 2 of the proxy rewrite

**Comment by suresttexas00** [comment]
I've tried many variations and I cannot get this packet to be parsed.  I tried teleporting in gm3 to another player...  I also tried clicking on the player to spectate from their view point.  No packet.

**Comment by JasonBristol** [comment]
The packet that gets sent is the CHANGE_GAME_STATE packet with {"reason": 3, "value": 3}

Reason 3 means game mode has changes, value of 3 means spectator mode

As long as this packet is being sent properly and is received by the server the game itself will handle providing the user spectator status as far as I can tell. I have no idea why the user would not have no clip enabled since I can see the proxy server parsed this packet successfully

```
[2016-04-13 01:25:40] [Wrapper.py/TRACE] [THREAD:Thread-14]: (PROXY SERVER) -> Parsed CHANGE_GAME_STATE packet:
{'reason': 3, 'value': 3.0}
```

***server.py***
```python
if pkid == self.pktCB.CHANGE_GAME_STATE:  # Change Game State
        data = self.read("ubyte:reason|float:value")
        if data["reason"] == 3:
            self.client.gamemode = data["value"]
        self.log.trace("(PROXY SERVER) -> Parsed CHANGE_GAME_STATE packet:\n%s", data)
```

Unless this is the culprit:

```python
data = self.read("ubyte:reason|float:value")
```

Elsewhere gamemode is being leveraged clearly as a uint, not a float.

**Comment by JasonBristol** [comment]
Adjusting `data = self.read("ubyte:reason|float:value")` to `data = self.read("ubyte:reason|ubyte:value")` appears to have no effect, issue still persists with clipping, but I suspect that this should have been ubyte to begin with

**Comment by suresttexas00** [comment]
float should be correct for game STATE ... change game state has nothing to do with game MODE.  This is the packet that tells the client to stop or stop raining, etc

**Comment by JasonBristol** [comment]
CHANGE_GAME_STATE is responsible for game state, but also for [game mode](http://wiki.vg/Protocol#Change_Game_State)

**Comment by suresttexas00** [comment]
"It appears when a bed can't be used as a spawn point and when the rain state changes." is what the description says, but then it lists the game mode change.. odd.  Never the less, since the problem does not occur in the development branch, which uses the same packet constants and packet parsing rules, out problem (likely) does not originate from the packet definitions or parsing formulas. (Unless the proxy fails to properly distinguish game versions and does not select the proper packet set... which would create much larger errors than we are seeing here).

The correct 1.9 packet ("serverbound19") is `CHANGE_GAME_STATE = 0x1e`

**Comment by suresttexas00** [comment]
same comment from #46:

"we should starting eye balling the playerlist packet...  and the uuid that is being sent with it... if a recall, player skin blobs are also sent in this packet.. and since my /van command is still not working (although the arguments are passed correctly now), the playerlist is defininately a suspect now... playerlist may even be affecting the spectator players."

**Comment by suresttexas00** [comment]
we will need a printout of the UUID (or any other suspect field) being sent.. this is another packet that mods uuids and sends the packet direct to the clients.

**Comment by suresttexas00** [comment]
Our problems is right here:
```
        if pkid == self.pktCB.PLAYER_LIST_ITEM:  # player list item
            if self.version > mcpacket.PROTOCOLv1_8START:
                head = self.read("varint:action|varint:length")
                z = 0
                while z < head["length"]:
                    serverUUID = self.read("uuid:uuid")["uuid"]
                    print("parsing CB.  ServerUUID is %s" % serverUUID)
                    playerclient = self.client.proxy.getClientByServerUUID(serverUUID)  # TODO  - check this ref
                    print("parsing CB. client is %s" % playerclient)
                    if not playerclient:
                        z += 1
                        continue
```
with only me on my test server, this results in the following when I login:
```
[19:32:22] [Wrapper.py/INFO]: SurestTexas00 logged in (UUID: 4f953255-6775-4dc6-a612-fb4230588eff | IP: 68.50.227.172)
parsing CB.  ServerUUID is 3269fd15-5be9-3c2a-af6c-12147a760f78
parsing CB. client is False
parsing CB.  ServerUUID is 3269fd15-5be9-3c2a-af6c-12147a760f78
parsing CB. client is False
[19:32:23] [Server thread/INFO]: SurestTexas00[/127.0.0.1:46043] logged in with entity id 168 at (3345.324383907087, 67.0, 2792.0453623128537)
[19:32:23] [Server thread/INFO]: SurestTexas00 joined the game
```

Now just have to see why `self.client.proxy.getClientByServerUUID(serverUUID)` is returning false.

**Comment by suresttexas00** [comment]
OK, well there is the problem.. you are getting the server by the offline client UUID (i.e., what is coming in the server packet).. however, the cleint uuid is actually the mojang UUID.. so they never match.  If there is not match, the logic is designed to allow the packet to pass unmolested to the client (which is a problem that masked this error- and one we should correct!).

**Comment by suresttexas00** [comment]
Its amazing what a little sleep and a fresh rum and coke will do for ya!

**Comment by suresttexas00** [comment]
I think the problem may be that the function getClientByServerUUID is SUPPOSED to search by offline UUID ("server" uuid), but is searching instead by online Uuid.

**Comment by suresttexas00** [comment]
the error is more subtle:  The strings are equal, yet they do not ''==".. perhaps we are comparing apples/objects to oranges/strings?

```
    def getClientByServerUUID(self, uuid):
        """ 
        This function expects uuid as a string
        """
        for client in self.clients:
            print("in getClientByServerUUID. server UUID is %s,\n"
                  "whereas passed uuid is %s" % (client.serverUUID.string,uuid))
            if client.serverUUID.string == uuid:
                print("in getClientByServerUUID they are equal %s" % uuid)
                self.uuidTranslate[uuid] = client.uuid.string
                return client
        # if uuid in self.uuidTranslate:
```


```
[20:03:39] [Wrapper.py/DEBUG]: "GET /user/profiles/4f95325567754dc6a612fb4230588eff/names HTTP/1.1" 200 26
[20:03:39] [Wrapper.py/INFO]: SurestTexas00 logged in (UUID: 4f953255-6775-4dc6-a612-fb4230588eff | IP: 68.50.227.172)
in getClientByServerUUID. server UUID is 3269fd15-5be9-3c2a-af6c-12147a760f78,
whereas passed uuid is 3269fd15-5be9-3c2a-af6c-12147a760f78
in getClientByServerUUID. server UUID is 3269fd15-5be9-3c2a-af6c-12147a760f78,
whereas passed uuid is 3269fd15-5be9-3c2a-af6c-12147a760f78
[20:03:39] [Server thread/INFO]: SurestTexas00[/127.0.0.1:46586] logged in with entity id 162 at (3345.324383907087, 67.0, 2792.0453623128537)
[20:03:39] [Server thread/INFO]: SurestTexas00 joined the game
in getClientByServerUUID. server UUID is 3269fd15-5be9-3c2a-af6c-12147a760f78,
whereas passed uuid is 3269fd15-5be9-3c2a-af6c-12147a760f78

```

**Comment by suresttexas00** [comment]
Error Fixed!!!  they are not the same type.. when I string the compared items, the print statement indicating equality is printed:
```
in getClientByServerUUID. server UUID is 3269fd15-5be9-3c2a-af6c-12147a760f78,
whereas passed uuid is 3269fd15-5be9-3c2a-af6c-12147a760f78
in getClientByServerUUID they are equal 3269fd15-5be9-3c2a-af6c-12147a760f78
```
I'll examine the types shortly and we can see what the proper way to code the fix will be!

**Comment by suresttexas00** [comment]
first thing is definitely to change the name of this function to getClientByOfflineServerUUID

**Comment by JasonBristol** [comment]
Interesting, `==` checks for value equality, `is` checks for identity, i.e. type, out of curiosity what was the type difference?

**Comment by suresttexas00** [comment]
and hte type difference is...
```
type of client.serverUUID.string is <type 'str'>
type of uuid is <class 'core.mcuuid.MCUUID'>
type of client.serverUUID.string is <type 'str'>
type of uuid is <class 'core.mcuuid.MCUUID'>
[20:40:55] [Server thread/INFO]: SurestTexas00[/127.0.0.1:54488] logged in with entity id 196 at (3344.943558054394, 67.0, 2790.589439641495)
[20:40:55] [Server thread/INFO]: SurestTexas00 joined the game
[20:41:14] [Server thread/INFO]: Turned off world auto-saving
type of client.serverUUID.string is <type 'str'>
type of uuid is <class 'core.mcuuid.MCUUID'>
type of client.serverUUID.string is <type 'str'>
type of uuid is <class 'core.mcuuid.MCUUID'>
type of client.serverUUID.string is <type 'str'>
type of uuid is <class 'core.mcuuid.MCUUID'>
[20:40:55] [Server thread/INFO]: SurestTexas00[/127.0.0.1:54488] logged in with entity id 196 at (3344.943558054394, 67.0, 2790.589439641495)
[20:40:55] [Server thread/INFO]: SurestTexas00 joined the game
[20:41:14] [Server thread/INFO]: Turned off world auto-saving
type of client.serverUUID.string is <type 'str'>
type of uuid is <class 'core.mcuuid.MCUUID'>
```

**Comment by suresttexas00** [comment]
So the question is now "how would you like to address this in the code?"  the cheap and dirty way is to str(uuid).. I am closing applicable issues related to this.

**Comment by JasonBristol** [comment]
change it to `client.serverUUID`, I must have thought it should have been a string, as a reference you can turn an MCUUID into a string by leveraging `.string` now

**Comment by suresttexas00** [comment]
so i could also just uuid.string?

**Comment by JasonBristol** [comment]
Yup if that is clearer then yah

**Comment by JasonBristol** [comment]
With the exception of a couple UUID functions, ***all*** uuids are being passed as MCUUID objects. This makes things a lot clearer for us going forward. When an operation needs a string uuid we can now just simply access the string attribute of the MCUUID object

**Comment by suresttexas00** [comment]
Is this the convention for the player api (player.getuuid) as well?  will plugin developers receive a string or a MCUUID object?

**Comment by JasonBristol** [comment]
They will receive an MCUUID object:

```python
self.uuid = self.wrapper.getUUID(username) # This is an MCUUID object
```

If your plugin needs this a string simply do the following:

```python
player.uuid.string
```

**Comment by suresttexas00** [comment]
ok... will keep this open to remind me that we need a section for player attributes as well as methods in the wiki.

**Comment by JasonBristol** [comment]
You read my mind, just spun up #53 for this purpose

**Comment by suresttexas00** [comment]
in proxy.base.py,

pycharm complains that `from core.mcuuid import MCUUID`
is and unused import.. does that sound right?  Is it getting inherited automatically from elsewhere?
```
from core.storage import Storage
from core.mcuuid import MCUUID
from client import Client
from packet import Packet
```

**Comment by JasonBristol** [comment]
You should be okay to remove that import, chances are it was an artifact of a previous body of work, this will aid #19
