### ISSUE TITLE
player.py api problem

### ISSUE THREAD

**Issue by suresttexas00** [suresttexas00/minecraft-wrapper#51]
This code, as you originally wrote it after the proxy rewrite was as follows:

```
import api

...

    def processColorCodesOld(self, message):
        """
        :param message: message text containing '&' to represent the chat formatting codes
        :return: mofified text containing the section sign (§) and the formatting code.
        """
        for i in API.colorCodes:
            message = message.replace("&" + i, "\xc2\xa7" + i)
        return message
```

Seeing that API did not resolve, I adjusted it to its present state in the code, which causes colorCodes to not be resolved:
```
import api as API

...

    def processColorCodesOld(self, message):
        """
        :param message: message text containing '&' to represent the chat formatting codes
        :return: mofified text containing the section sign (§) and the formatting code.
        """
        for i in API.colorCodes:
            message = message.replace("&" + i, "\xc2\xa7" + i)
        return message
```

I think the proper way is probably as so, which removes all the errors
```
import api.base

....

    def processColorCodesOld(self, message):
        """
        :param message: message text containing '&' to represent the chat formatting codes
        :return: mofified text containing the section sign (§) and the formatting code.
        """
        for i in api.base.API.colorCodes:
            message = message.replace("&" + i, "\xc2\xa7" + i)
        return message

**Comment by JasonBristol** [comment]
`from api.base import API` would be more succinct and should allow you to use `API.colorCodes`, this was definitely my error, must have missed this when I created `base.py`

**Comment by JasonBristol** [comment]
Feel free to submit a PR with your changes for #47 and this one when ready, we can review and merge

**Comment by suresttexas00** [comment]
thanks for the reminder... we can do this with whatever fix is the correction for getClientByServerUUID, which also needs renamed to getClientByOfflineServerUUID

**Comment by suresttexas00** [comment]
I also tried `from api.base import API` and that did not work for some reason either (I agree that seemed the logical fix.. but......)

**Comment by JasonBristol** [comment]
Oh wait you know what, you need to run `from base import API` since player is in the `api` module already, didn't notice that initially here

**Comment by suresttexas00** [comment]
Forgot this just now with last PR :(  i'll test the `from base import API` if that is preferred.

**Comment by JasonBristol** [comment]
Sure, give that one a try, I forget if that worked or not, but import api.base definitely will work.

If we can make wrapper a real python package all of our imports will be much cleaner and wrapper will gain the benefit of other python facilities. This would be as simple as setting up a `setup.py` file, and setup tools will add wrapper to the python path automatically allowing for relative imports.

I may include this ins #19 since it makes the most sense and does not change how wrapper works

**Comment by suresttexas00** [comment]
that seems to work.
