### ISSUE TITLE
Update Documentation & Wiki

### ISSUE THREAD

**Issue by JasonBristol** [suresttexas00/minecraft-wrapper#53]
Once we have a stable release we should flesh out documentation and our wiki page. Key points below:

- [ ] Proxy (server & client)
- [ ] Plugin Development
- [ ] MCUUID
- [ ] Importing and using base wrapper modules
- [ ] Logging Configuration
- [ ] Player object accessors and methods

There are many more, but these are the big ones. If I missed any please indicate that in this thread.

**Comment by suresttexas00** [comment]
I have added a resource page to this branches wiki.  The important item is a link to the last 1.8 wiki on the minecraft protocol (version 47).  This is where we will need to go to add new packets for 1.8 to proxy.  we can add more links for other versions 1.7, 1.6.4, etc....

**Comment by suresttexas00** [comment]
wiki is now maintained on Ben's Page.
