### ISSUE TITLE
Add Mac support for terminal colors

### ISSUE THREAD

**Issue by JasonBristol** [suresttexas00/minecraft-wrapper#54]
Adjust logging to allow macs ANSI terminal output

**Comment by suresttexas00** [comment]
Staged release 1 will not be a release candidate.. just a continuation of BenBaptist development.  This issue does not need fixing for the development since it functions just as well as the currect development. I have notes on these criteria on the milestone.

**Comment by suresttexas00** [comment]
This is not needed for the Staged release 1 milestone.  This can remain unfixed until staged release 2 or the actual release candidate 1.  read the criteria under the staged release 1 milestone.

**Comment by JasonBristol** [comment]
This adjustment is a single string, there should be no reason to not append it to release 1

**Comment by suresttexas00** [comment]
okee dokee

**Comment by JasonBristol** [comment]
Beginning work on this and patch 5
