### ISSUE TITLE
Ban code needs to use local server json files

### ISSUE THREAD

**Issue by suresttexas00** [suresttexas00/minecraft-wrapper#57]
- [x] Both uuid and IP bans need to use the vanilla json files, that way the bans still work if the server is ever put in online mode.  
- [x] Ban UUID is non functional and needs to be working
- [x] The whole "/proxy-ban-ip", etc needs to go away.. the proxy ban commands should just be ban-ip and ban (over ride the server versions while in proxy mode).
- [x] Add ban reasons
- [x] Add ban-ip in same fashion as banuuid in proxy base
- [x] Add expiration (optional) in banfiles
- [x] Make the ban code effective in proxy.client (with new ban file locations) again for IP bans.
- [x] Implement bans in proxy.client for uuid bans
- [x] Fix isUUIDBanned
- [x] Fix isAddressBanned
- [x] Fix pardonIP
- [x] Add pardon (player uuid)  
- [x] Add command-level interface for /ban-ip and /pardon-ip (commands.py)
- [ ] ...that was a lot of changes; test the durn thing.

__Before releasing Staged Release 1 (and before development is pulled by BenBaptist), I need to complete the tasks above__

**Comment by suresttexas00** [comment]
well, I have to get up early tomorrow, so no late-night tirades and confusion for me.. I'll work on this tomorrow after the player.rawMessage and chatBox investigations.

**Comment by suresttexas00** [comment]
so far (imports not shown):

proxy.base
```
    def banUUID(self, uuid, reason="The Ban Hammer has spoken!", source="Wrapper", expires="forever"):
        """
        Ban someone by UUID  This is low-level... calling function must determine UUID
        :param uuid - uuid to ban (MCUUID)
        :param reason - text reason for ban
        :param source - source (author/op) of ban.
        :param expires - expiration.  Field not supported by vanilla server - implement it for tempbans in future?

        This probably only works on 1.7.10 servers or later
        """
        banlist = get_jsonFile("banned-players")
        if banlist is not False:  # file and directory exist.
            if banlist is None:  # file was empty or not valid
                banlist= dict()  # ensure valid dict before operating on it
            if find_iteminJsonlist(banlist,"uuid", uuid.string):
                return "player already banned"  # error text
            else:
                name = self.wrapper.lookupUsernamebyUUID(uuid.string)
                banlist.append({"uuid": uuid.string,
                                "name": name,
                                "created": time.time(),
                                "source": source,
                                "expires": expires,
                                "reason": reason})
                if put_jsonFile(banlist, "banned-players"):
                    self.wrapper.server.console("kick %s Banned: %s" % (name, reason))
                    return "Banned %s: %s" % (name, reason)
                return "Could not write banlist to disk"
        else:
            return "Banlist not found on disk"
```

new helpers:
```
def get_jsonFile(filename, directory="./"):
    """
    :param filename: filename without extension
    :param directory: by default, wrapper script directory.
    :returns a dictionary if successful. If unsuccessful; None/no data or False (if file/directory not found)
    """
    if os.path.exists("%s%s.json" % (directory, filename)):
        with open("%s%s.json" % (directory, filename), "r") as f:
            try:
                return json.loads(f.read())
            except ValueError:
                return None
            #  Exit yielding None (no data)
    else: return False  # bad directory or filename

def put_jsonFile(data, filename, directory="./", indent_spaces=2):
    """
    writes entire data to a json file.
    This is not for appending items to an existing file!

    :param data - json dictionary to write
    :param filename: filename without extension
    :param directory: by default, wrapper script directory.
    :param indent_spaces - indentation level. Pass None for no indents. 2 is the default.
    :returns True if successful. If unsuccessful; None = TypeError, False = file/directory not found/accessible
    """
    if os.path.exists(directory):
        with open("%s%s.json" % (directory, filename), "w") as f:
            try:
                f.write(json.dumps(data, indent=indent_spaces))
            except TypeError:
                return None
            return True
    return False

def find_iteminJsonlist(jsonlist, keyname, searchvalue):
    for items in jsonlist:
        if items[keyname] == searchvalue:
            return items
    return None
```

**Comment by suresttexas00** [comment]
Do you have a suggestion on code for this mess:
```
                    if len(get_args(payload["args"], 0)) > 0:
                        ipnumbers = str(get_args(payload["args"], 0)).split(".")
                        if len(ipnumbers) != 4:
                            player.message("&cInvalid IP address format: %s" % get_args(payload["args"], 0))
                            return False
                        for ipnumber in xrange(0, 4):
                            if int(ipnumbers[ipnumber]) > 255 or int(ipnumbers[ipnumber]) < 0:
                                player.message("&cInvalid IP component: %s  &5%s" % (get_args(payload["args"], 0), str(ipnumbers[ipnumber])))
                                return False
```

**Comment by JasonBristol** [comment]
yah, we should use a library function already imported via the `socket` package:

```python
ipaddress = str(get_args(payload["args"], 0)))
try:
    self.socket.inet_aton(ipaddress) # Attempts to convert to an IPv4 address
except socket.error as e: # If it fails, the ip is not in a valid format
    player.message("&cInvalid IP address: %s" % ipaddress)
```

This follows an EAFP (Easier to Ask Forgiveness than Permission) format, i.e. instead of trying to validate the ip address manually, lets try to apply it to a use case and catch it if it fails

**Comment by suresttexas00** [comment]
The real thing to do is use IPy which also supports ipv6.. but for now...

**Comment by suresttexas00** [comment]
i never met an ipv4 that I could not ban between 0.0.0.0 and  255.255.255.255.. the socket thing is hacky and allows unexpected values to be good (ones we would not use in minecraft, like 4 or 44.12)

**Comment by JasonBristol** [comment]
That would create an external depencency that isn't really needed, 4 and 44.12 get padded with zeros i.e. 0.0.0.4 and 0.0.44.12 which are technically ip addresses

**Comment by suresttexas00** [comment]
if you mean IPy.. I agree

**Comment by JasonBristol** [comment]
We shouldn't be creating any more logic than necessary, honestly if some guy connected to my server with an ip of 0.0.0.4 I would be curious but wouldn't care after I banned him

**Comment by suresttexas00** [comment]
I dont like EAFP for this application.. what if the user meant 4.4.0.0, not 0.0.4.4?

**Comment by JasonBristol** [comment]
Then the user needs to enter "4.4.0.0"

**Comment by suresttexas00** [comment]
Just not good to be loosy goosy with this.

**Comment by suresttexas00** [comment]
Some of my staff are only 12 LOL

**Comment by JasonBristol** [comment]
What is the risk? Say I do enter /ipban 4, ip 0.0.0.4 gets banned, the chances of someone having that ip are almost zero, but say someone was on, they get banned. You can unban them in the same way, /unban 4

The risk is the same as saying /ipban 192.168.1.1 but meaning /ipban 192.168.1.2, it comes down to operator error

**Comment by JasonBristol** [comment]
Using this methodology also gives us the capability to ban via IPv6 addresses -- `self.socket.inet_pton(ipaddress)`

**Comment by suresttexas00** [comment]
what is the return on banning an incorrect address and having no idea you banned an incorrect address?
what if you just forgot a last number? instead of a "hey dummy" message, you silently ban 0.192.168.1; and everything seems fine until they hacker logs on with 5 more alt accounts and you wonder how he got on... (proxies aside..)

**Comment by suresttexas00** [comment]
I'm more interesting in making sure the RIGHT person got banned than worrying about banning the wrong person (which is a statistical improbability anyway).

**Comment by JasonBristol** [comment]
Same exact risk if I mistyped an octet in the IP address as my example illustrated

**Comment by suresttexas00** [comment]
but why not catch something so obvious?

**Comment by suresttexas00** [comment]
nobody i know takes shortcuts by letting 0 padding do their work for them.

**Comment by suresttexas00** [comment]
but i agree we need to think forward to ipv6

**Comment by JasonBristol** [comment]
Ultimately the issue is mistyping an ip address, we can't prevent that from happening, adding more boilerplate validation logic won't really add any value against this.

If it is really a concern, you can do::

```python
ipaddress = str(get_args(payload["args"], 0)))
try:
    if len(ipaddress.split(".")) == 4:
        self.socket.inet_aton(ipaddress) # Attempts to convert to an IPv4 address
    else:
        raise "IP address is not in a valid format: %s" % ipaddress
except socket.error as e: # If it fails, the ip is not in a valid format
    player.message("&cInvalid IP address: %s" % ipaddress)
except Exception as ex:
    player.message("&c%s" % e)
```

**Comment by JasonBristol** [comment]
In python 3 we will get the `ipaddress` package baked in which does pretty much the same thing

**Comment by suresttexas00** [comment]
continue tomorrow.. :)

**Comment by JasonBristol** [comment]
I believe you are already working on this one so will tag you for this

**Comment by suresttexas00** [comment]
due to the messy nature of commands.py, for now, I am going to implement the bans user interface from the minecraft plugin api, so there will be no /ban /bap-ip, etc from the console or game client command interface (other than the default vanilla server ones which operate on the local offline server).

**Comment by suresttexas00** [comment]
???
```
    def pardonUUID(self, uuid):
        banlist = get_jsonFile("banned-playerss")
        if banlist is not False:  # file and directory exist.
            if banlist is None:  # file was empty or not valid
                return "No bans have ever been recorded..?"
            #print "hello".__str__()
            # should I be using this for uuid? what if a string gets passed instead? should I use .__str__ instead?
            # __str__ should work for MCUUID and str objects, correct?
            banrecord = find_iteminJsonlist(banlist, "uuid", uuid.string)
            if banrecord:
  ```

I guess as long as I am always using MCUUID objects, we are OK?

**Comment by suresttexas00** [comment]
Ok, well I'll add a basic /ban /ban-ip /pardon /pardon-ip to commands, but it will not be fancy (will not pass anything more than player/ip... no expirations, reasons, sourcename, etc...

**Comment by suresttexas00** [comment]
Testing has not went as well as I hoped.  However, the ban-ip, pardon-ip and automatic pardoning if the ban expires are all functional.  All the ban code is using the vanilla objects.  There are some bugs... mostly in that I can't seem to nail down when a UUID is just a string or MCUUID object, which is causing headaches in trying to determine when to `str(uuid)`, `uuid.__str__`, or `uuid.string`... but for now, this functions at a high enough level for Staged Release 1, as it meets better than development branch functionality. PR shortly..

**Comment by JasonBristol** [comment]
Using `uuid.__str__` is the less prefered way to say `str(uuid)`. In regards to MCUUID I tried commenting all areas where it would be an MCUUID object. If it is an object use `uuid.string` if you need a string.

**Comment by suresttexas00** [comment]
Ill have the changes coming in two different PR's because one of them is against core.wrapper.py... And I dont want conflicts on the whole PR if one of your changes conflicts mine ;)

**Comment by suresttexas00** [comment]
So you can start looking at what I did

**Comment by suresttexas00** [comment]
Everything is pulled, all the way back to staging.  I am going to want to test staging further before it goes live on my server and then to development.

**Comment by suresttexas00** [comment]
I won't be as concerned about future stages.
