### ISSUE TITLE
Refactor Wrapper Version and Release Pipeline

### ISSUE THREAD

**Issue by JasonBristol** [suresttexas00/minecraft-wrapper#59]
Fully understanding the potential pushback from this one, I would still like to mark this issue clearly so as to have a logical and in depth discussion with the core focus on the health and quality of Wrapper.py.

While many may have differing opinions on what version scheme to use, we should not shy away from discussing a real versioning scheme that works toward quality automation within wrapper and external systems.

If you are not familiar with [Semantic Versioning](http://semver.org/) I suggest giving it a serious look as it is leveraged by a lion's share of modern codebases and has been adopted as the de-facto standard.

As of today Wrapper.py sits at version 0.7.7 -- this in semantic versioning terms means that it has not even hit an official stable release yet (I think we agree that this is accurate). With the intent of this fork being to stabilize Wrapper.py, as well as incorporate features that some would grant as required to provide value in various areas, we should consider a v1.0.0-rc1 release.

Abiding by our branch philosophy would mean that we could develop our development branch to an indefinite point, providing a PR to BenBaptist/Development whenever necessary. Ben could very well log on to have a PR that advances Wrapper far beyond just simple bug fixes, but rather a backlog of changes that mature Wrapper. This is ***okay***, source control implemented correctly mandates a division that does not risk *touching* the quasi "golden state" of BenBaptist/Master until explicitly desired.

With that in mind, and adopting semantic versioning as our version schema, I have already staged `utils.version.py` in our experimental branch for further development. PEP compliant and borrowed from Django, `version.py` will allow us to automatically rev, fetch, and compare versions in a way that utterly deprecates facilities like `build_script.py`.

<hr>

Before the issue of the MD5 checksum comes up, lets review the use case of such a checksum.

When Wrapper.py automatically looks for and fetches updates, as of today, it sends a raw HTTP request to github to read out our `build/` directory and `globals.py`. It leverages a combination of comparing the checksum as well as the version number to validate that an update is available. This ***does work***, but let me suggest a more robust and modular way that is hinted at in `version.py` and is leveraged by many other mature implementations:

The very act of using git as a source control engine means that each and every commit has a checksum generated. Why store our own poor man's checksum when we can simply leverage this functionality through say `git log --pretty=format:%ct --quiet -1 HEAD`?

Further to this point, is a checksum even needed for automatic updates at all? If we were to remote fetch any development or master updates through git, we would not need to worry about the integrity of the content.

Here is what I propose for Feature Pack 1:

- Adopt Semantic Versioning as our versioning standard
- Refactor our versioning implementation to leverage the full breadth of `version.py`
- Refactor automatic updates to fetch directly through git via `git remote update` and `git show-branch *<branch>`
- Assume that checksum is desired for public external repositories and fetch from HEAD

These changes serve more than just cosmetic purposes, this enables us to do one of several things for the future:

- Re-point reference repositories for automatic updates, this gives users the ability to pull updates from alternative sources such as forks (#31).
- Automatic versioning via commit, i.e. each commit would update the full version as enabled by `version.py`, this allows for fine grain versioning and could help build test driven plugins for automated testing.
- Automated changelogs

Use this thread as a discussion panel

**Comment by suresttexas00** [comment]
I agree.  I do think this post (for discussion and to generate attention) should be housed on Ben's fork.

**Comment by JasonBristol** [comment]
Lets create an issue with a link to this thread, I would still like to use this one as Ben's issue board is often neglected

**Comment by suresttexas00** [comment]
I hate to say it.. the pushback on this is going to boil down (to a lesser degree) to PEP-8 and (to a MAJOR degree).. __tabs__ D: ... Ben hates spaces... I would like to hope this is something he can overlook, especially since there is more community development and everything is not on his shoulders.

**Comment by JasonBristol** [comment]
My old professor would give us a 0 if we used tabs. The issue with tabs is it is 100% environment specific. I might have tabs set to 4 spaces on my machine, but Ben is using tabs of 2 spaces, when I take a look at his source it is jumbled. With python being indentation aware, this is absolutely critical.

My personal take on this, Ben should use Sublime text or an editor that can convert spaces to tabs and visa versa automatically or via hotkey. This is what I have to do each and every time I sample some of his code. The code itself should be sanitized and leverage spaces. For me there is no discussion on this matter as it relates to general coding best practices and should not be based on preference.

**Comment by suresttexas00** [comment]
there are also problems with aligning indented text (like dictionaries, etc) that do not have the same level of indent as your tab.

**Comment by benbaptist** [comment]
I think the double tabs is a result of everyone's editors mixing things up and changing stuff - I've noticed that happening too. I didn't really care at this point, you can use spaces. I probably won't be editing the code with nano and such frequently since I don't get to maintain it as much.

**Comment by suresttexas00** [comment]
Moved to Ben's page
