### ISSUE TITLE
Feature List - handle name changes properly

### ISSUE THREAD

**Issue by suresttexas00** [suresttexas00/minecraft-wrapper#61]
- [x] Add IP to wrapper.usercache at each login. - possible use for this could be to allow user logins when auth servers are down, provided they login from same IP as last connect...
- [x] Add tempban functionality
- [ ] When name changes occur, add option to convert local player name by changing the name and the offline filenames in `serverFolder/world/playerdata/<uuid>.dat` and `serverFolder/world/stats/<uuid>.json`
- [x] Continue to finish docstrings for player api in preparation for more complete reference. (#15) 
- [x] Add standard player api method for getting offline UUID... include it as one of the self. items like uuid and username presently. 
- [x] Check EULA and fix `Fresh install of Wrapper.py in certain conditions does this thing` (#262) 
- [x] Add useBed event to proxy mode.
  Player.py Add:
- [x] <del>Methods to get</del> offlineuuid(), getIP() - changed to properties which are loaded by clientconnection.
- [.] <del>Add more payload to clicking events (place, dig, interact) to send raw int() for location (in addition to the present location tuple).  This would allow plugins like protection/loggers to have the location already packed for storage.</del>

**Comment by JasonBristol** [comment]
Adding this to Feature Pack 1 since it includes net new functionality

**Comment by suresttexas00** [comment]
Some items I want to get into the staged release 1 - in particular, where the ban code records bans (vanilla server json files).  I don't want tow "versions" out there writing to different places (wrappers '/wrapper-data/json/proxy-data.json' versus the banned-ip/players in the vanilla folder.

**Comment by suresttexas00** [comment]
It's a similar situation to not being finished with the logger.json files... you don't want users having to regenerate that all the time.

**Comment by JasonBristol** [comment]
Lets mark this for feature pack 1 and check off what items we complete for staged release 1.

I agree, but as of right now I can't think of a clean solution, we wouldn't want to automatically decide to regenerate their logging config for them either since that could blow away their customizations.

A potential solution would be to rename the old logging.json to logging.json.old and write a fresh one that is compatible with the new version. This should be simple, I will spin an issue off to track it

**Comment by suresttexas00** [comment]
actually, you are correct, I already have #57 to cover this.

**Comment by JasonBristol** [comment]
In regards to the EULA, I think we can safely check for `eula.txt` and overwrite it to `true` on startup. This would also prevent the almost nonexistent chance that it was reset to false.

**Comment by JasonBristol** [comment]
EULA auto acceptance has been packaged with patch 7 (#96)

**Comment by suresttexas00** [comment]
#355 in Ben's repo.
