### ISSUE TITLE
Relogging as Spectator disables noclip

### ISSUE THREAD

**Issue by JasonBristol** [suresttexas00/minecraft-wrapper#62]
This is a legacy issue that has existed where a user disconnecting in spectator mode will not be able to clip through objects until they are reissued spectator mode.

Potentially related to the cache?

**Comment by suresttexas00** [comment]
I have not tested this in a while.  I used to notice this on my server.  I suppose I stopped noticing this because one of my plugins is now issuing gm 0 when a player logs on (which means I fall or get stuck in walls after I log back in oftentimes LOL).

**Comment by suresttexas00** [comment]
I'm note sure if it is a minecraft or wrapper issue honestly... It does behave similar to our last issue with gm3 and I have noticed during my testing that the server routinely sends playerlistitem's upon player connect.. which would presumably correct this issue...

**Comment by JasonBristol** [comment]
Yah I am not sure either to be honest, I remember digging into the issue before and I recall it being minecraft related, but I am not 100% sure

**Comment by suresttexas00** [comment]
maybe that is why the playerlist packet seems to be sent so frequently now, even when other players are not on...

**Comment by suresttexas00** [comment]
This is a wrapper issue, not a problem with an un-wrapped vanilla server.

However, this may not be easy to track down, has existed in wrapper for a long time, and does not meet Staged Release 1 criteria:

**Staged Release 1**
 Due by April 30, 2016   Last updated 11 minutes ago
Get a stable 'staged' release with no bugs. _**"No bugs" being defined as no new bugs and the wrapper performs as it presently does on the development branch, or better.**_ Once stable staged release 1 in done, experimental can continue with further rewrites and refactoring.

Let's not hold up SR1 for this issue.

**Comment by suresttexas00** [comment]
Hopefully, continued refactoring ought to bring this to light.

**Comment by suresttexas00** [comment]
This is a pernicious one and I still have no idea what causes it.

**Comment by suresttexas00** [comment]
It appears that the client after logoff/login believes it has relogged in spectator.  Apparently, the server believes the client should be in the default gamemode (usually survival).  The server enforces survival rules for clipping.

**Comment by suresttexas00** [comment]
#351 in Ben's repo.
