### ISSUE TITLE
Global Variable Descoping

### ISSUE THREAD

**Issue by JasonBristol** [suresttexas00/minecraft-wrapper#7]
We should not rely so heavily on global variables, these already have a proven track record for causing issues within wrapper.

Directly from [The Hitchhiker's Guide to Python](http://docs.python-guide.org/en/latest/) which states in clearer terms than I can:

> Heavy usage of global state or context: instead of explicitly passing (height, width, type,wood) to each other, Table and Carpenter rely on global variables that can be modified and are modified on the fly by different agents. You need to scrutinize all access to these global variables to understand why a rectangular table became a square, and discover that remote template code is also modifying this context, messing with table dimensions.

**Comment by suresttexas00** [comment]
What are some examples you are thinking of?

**Comment by JasonBristol** [comment]
I think I have been looking at this for too long today, it looks like most if not all of our class attributes are initialized, this is most likely a non-issue and could probably be closed

**Comment by suresttexas00** [comment]
Feel free to close whatever you think has been resolved.
