### ISSUE TITLE
Universal Connect

### ISSUE THREAD

**Issue by JasonBristol** [suresttexas00/minecraft-wrapper#70]
I am just looking to understand the end goal of Universal Connect a little better. From what I have seen in the code as well as our touch points on it, it is a way to abstract server and client versions providing what I assume is the ability for a 1.9 server to host 1.8 players or visa versa?

**Comment by suresttexas00** [comment]
yes, that is the seed of it.  it will need to be developed.  It was a short-term necessity between 1.9.1 and 1.9.2, but with the adoption of 1.9.2 as the de-facto 1.9 version, it slipped into the background.

**Comment by JasonBristol** [comment]
I can see a sizable body of work going into this functionality. From the standpoint of my server it would be awesome if this could also provide some configuration in wrapper.properties that would allow us to configure what version range we would want to allow universal connect to handshake.

It would sit under an "Advanced" section I was thinking about adding, but needed a good reason too, this fits

**Comment by JasonBristol** [comment]
Should we create a milestone dedicated to UC since it looks like a deliverable by itself

**Comment by suresttexas00** [comment]
yes.. a long range one.. this should probably be done AFTER the proxy refactor is done.
