### ISSUE TITLE
Regenerate logging.json when backwards incompatible changes are made

### ISSUE THREAD

**Issue by JasonBristol** [suresttexas00/minecraft-wrapper#71]
We want to stay away from making impacting decisions against administrators server configuration, but in the case of backwards incompatible changes pushed out in a new release of wrapper, we need to ensure that their servers don't bust.

In these cases we should provide clear logging that their logging configuration is being regenerated and that their old one is being renamed `logging.json.old`.

If feasible, it would be even better if we could parse out their current configuration and apply it to a new configuration that is compatible. This should be straightforward since manipulating a dictionary parsed from json is elementary

**Comment by suresttexas00** [comment]
I would also like to see both the logging.json and the wrapper.properties files get moved to /wrapper-data

**Comment by JasonBristol** [comment]
Easily doable once we have #78

**Comment by suresttexas00** [comment]
How is this coming?

**Comment by JasonBristol** [comment]
Somewhat tricky since there is no way to mark a configuration file with any kind of indicator of its version. This means we have no real way to inspect whether a config is deprecated or not. For now I think what I will do is attempt to load it, and perform the retrofit if it fails

**Comment by suresttexas00** [comment]
ok

**Comment by JasonBristol** [comment]
What is the haste with Staged Release 1? This can absolutely make it into the release without waiting another month

**Comment by JasonBristol** [comment]
Technically if we are following our release dates, Staged Release 1 is 14 days out

**Comment by suresttexas00** [comment]
The date is a due date (deadline), not a "projected" date.

The rush is I want this to be what Ben pulls back to development (not the crappy developement PR I presently have waiting for him).  For all I know, he may get a hair and decide the pull it tomorrow.

**Comment by suresttexas00** [comment]
The current PR to his development is going to cause conflicts with the new ban schema...

**Comment by JasonBristol** [comment]
So will we be merging this into staging, testing for a few days, then moving this into our dev branch before submitting to Ben's dev? This will make sure all of our branches are up to date, our dev branch is a snapshot of a stable base, and that our current code set is bug free. This will also free us up for more development in experimental and staging since it may take Ben a month to accept the PR

**Comment by suresttexas00** [comment]
yep! that is the plan.

**Comment by JasonBristol** [comment]
Awesome, will pull down your updates, should have a PR for this one by tomorrow since it is late here

**Comment by JasonBristol** [comment]
Meh got sick this weekend, will push an update for this and #88 tonight

**Comment by suresttexas00** [comment]
I can do #88, provided you tell me what fmt is intended to be...

**Comment by suresttexas00** [comment]
I will push a PR for this now.. just to correct the pid part, at least (for continued testing).

**Comment by JasonBristol** [comment]
Yah not 100% sure what fmt does off the top of my head, will need to take a
look, will include at least a fix for that part in tonight's PR

**Comment by suresttexas00** [comment]
I'm going to push SR1 now.  If you get this done before BB pulls it, I will include it as well, but no rush.

**Comment by JasonBristol** [comment]
It does not look like `dictConfig()` will throw an error for a configuration file, as long as it is valid json and all required params are met it will successfully load the config. The errors we see during an invalid config are when we actually attempt to log. The log message will run against the configured formatter and it is the actual formatter that throws an error.

Because of this I am not sure there is much we can do automagically for the end user other than make it clear that a certain Wrapper update will require a regenerated configuration.

I will be pushing some minor adjustments to the log class to make log files more dynamic

**Comment by JasonBristol** [comment]
Ultimately I actually think this one can be closed. The original issue surfaced when we were using a custom dict entry into the formatter, this no longer exists so we should never see an error like this again unless the following is true:

1. We remove a custom formatter, handler, or filter from the logging module. This would be rare, but regardless would require a configuration change. In this instance we should force the default logging configuration.

2. We add a custom formatter, handler, or filter from the logging module. This is not as rare, but again we would want to force the default configuration.

<hr>
__Why should we force the default configuration? Wouldn't this blow away customizations?__

- First we would need to classify customizations. Are we talking a user has adjusted their console stream to only print ERROR messages via `level`? If so then us resetting this is not going to break anything. At most this is a very very minor annoyance that actually prevents disruptive changes. Are we talking the user has gone into the source and defined their own handlers? Then this is not something we really support. At most, the user is already comfortable enough with the source to customize their own fork and they have not taken their configuration file into account. The resolution would be fore them to regenerate it manually. Ultimately this is a non issue for us in this case.

As always, changes like these would be provided in patch notes. We would be overwriting their current configuration to prevent any issues, at worst this causes a minor annoyance, at best we backup their old configuration.

The real issue comes down to detecting a change like this. Should we set a one off variable to say "at first launch overwrite the config"

This gets sticky because how are we supposed to know that this is the first launch after the patch?

A potential way is assuming that the user is __only__ patching via our automatic updates, in which part of our update is to determine if a non compatible logging change was made, forcing a refresh. This could easily be set at the `globals` level, or better yet via the mechanism described in #59.

<hr>

At the end of the day, this issue seems to be non-impacting for the time being. Once we adjust our version control we can better manage our updates (#59), which would really make this issue non-existent.

For now I will close this issue and push my adjustments in patch 7.
