### ISSUE TITLE
Consolidate and flesh out permissions.py

### ISSUE THREAD

**Issue by JasonBristol** [suresttexas00/minecraft-wrapper#72]
What was the intended purpose of permissions.py? Was it to create individual objects that related to a permissions or was it to consolidate permissions logic?

Currently:

**_api.permissions.py**_

``` python
# -*- coding: utf-8 -*-

# More stuff will probably go here soon.
class Permissions:

    def __init__(self):
        pass
```

**_core.permissions.py**_

``` python
# -*- coding: utf-8 -*-

# This module is not used, but may be useful for pulling out permissions logic

class Permissions:

    def __init__(self, wrapper):
        self.wrapper = wrapper
        #self.permissions = storage.Storage("permissions")

    def createGroup(self, groupName):
        if groupName in self.permissions["groups"]:
            raise Exception("Group '%s' already exists!" % groupName)
        else:
            self.permissions["groups"]

    def doesGroupExist(self, groupName):
        return groupName in self.permissions["groups"]

    # Check for permissions
    def doesPlayerHavePermission(self, player, node):
        uuid = player.uuid # This would be an MCUUID object
```

**Comment by suresttexas00** [comment]
I think ben wanted to originally move the whole of permissions to this file.

**Comment by JasonBristol** [comment]
I think that would be beneficial as well, particularly under the api module since this would also be leveraged by plugins

**Comment by JasonBristol** [comment]
I really would like to see this go into FP 1 if at all possible.

**Comment by JasonBristol** [comment]
Moving this to FP 1

**Comment by suresttexas00** [comment]
I think the api.permissions was just old code.  I think core.permissions is where the permission code would need to go (eventually?)

**Comment by suresttexas00** [comment]
Dead issue on this repo.
