### ISSUE TITLE
Dynamically fetch entities

### ISSUE THREAD

**Issue by JasonBristol** [suresttexas00/minecraft-wrapper#73]
***entities.py***

```python
ENTITIES = {  # Unfinished list of entities
    48: {"Name": "Mob"},
    49: {"Name": "Monster"},
    50: {"Name": "Creeper", "size": (0.6, 1.8)},
    51: {"Name": "Skeleton", "size": (0.6, 1.8)},
    52: {"Name": "Spider", "size": (1.4, 0.9)},
    53: {"Name": "Giant Zombie", "size": (3.6, 10.8)},
    54: {"Name": "Zombie", "size": (0.6, 1.8)},
    55: {"Name": "Slime", "size": (0.6, 0.6)},
    56: {"Name": "Ghast", "size": (4, 4)},
    57: {"Name": "Zombie Pigman", "size": (0.6, 1.8)},
    58: {"Name": "Enderman", "size": (0.6, 2.9)},
    90: {"Name": "Pig"},
    91: {"Name": "Sheep"},
    92: {"Name": "Cow"},
    93: {"Name": "Chicken"},
    94: {"Name": "Squid"}
}
```

What is the end goal for entities.py? Right now it looks like it is only leveraged for certain packets

**Comment by suresttexas00** [comment]
This is future stuff... there a open issues on future functionality. For instance https://github.com/benbaptist/minecraft-wrapper/issues/149

**Comment by JasonBristol** [comment]
Might be a good candidate for FP 2 since this looks more involved at first glance, will need to do some significant adjustments, what do you think?

**Comment by suresttexas00** [comment]
we definitely have more on our plate than we need at the moment... it can wait

**Comment by JasonBristol** [comment]
This is why I was suggesting FP 2 which currently has no date...

**Comment by JasonBristol** [comment]
I am organizing all of our items into releases so we can focus our efforts

**Comment by suresttexas00** [comment]
https://github.com/suresttexas00/minecraft-wrapper/commit/e98263a5fb3eef1415ac9eac69d0108dc451008d
