### ISSUE TITLE
Remove auth.py from wrapper

### ISSUE THREAD

**Issue by JasonBristol** [suresttexas00/minecraft-wrapper#74]
Currently an empty file, but its name is interesting

**Comment by suresttexas00** [comment]
I have no idea....

**Comment by suresttexas00** [comment]
this might be stuff he has discussed about making a wrapper that could connect to an online server via proxy mode (the way bungee/spigot does)

**Comment by JasonBristol** [comment]
Interesting

**Comment by JasonBristol** [comment]
For now I think we can remove this file since it does nothing, if this idea hits our plate again we can address it in a release

**Comment by JasonBristol** [comment]
Patch 8 will remove this file
