### ISSUE TITLE
Separate wrapper and server artifacts into separate folders

### ISSUE THREAD

**Issue by suresttexas00** [suresttexas00/minecraft-wrapper#78]
This was never pulled by Ben.  I think we can create a slightly more elegant version by defining a self variable early on and use it everywhere it's needed, versus the cumbersome config reference.

https://github.com/benbaptist/minecraft-wrapper/pull/171

I am thinking these variables (which could be identically set for keeping things like they are now):
self.wrapper_dir
self.server_dir

EDIT:

> clarification.. separate wrapper artifacts from the "server folder".. in some cases, they may still be kept in the /server/world/plugins folder (storage objects, per the api, can be in the world/plugins folder or the wrapper /wrapper-data folder (or something like that).. As in the whole wrapper should be independent of the server folder:

>/wrapper
/serverfolder

**Comment by JasonBristol** [comment]
Agreed, this should be straightforward to implement

**Comment by suresttexas00** [comment]
clarification.. separate wrapper artifacts from the "server folder".. in some cases, they may still be kept in the world folder (storage objects, per the api, can be in the world/plugins folder or the wrapper-data folder (or something like that).. As in the whole wrapper taken out of and independent of the server folder:

/wrapper
/serverfolder

**Comment by JasonBristol** [comment]
Ahh I see now, will adjust back

**Comment by suresttexas00** [comment]
Also to be clear, we don't want this started before Staged Release 1...

**Comment by JasonBristol** [comment]
This is a part of FP 1

**Comment by JasonBristol** [comment]
`/wrapper` would also include `logging.json`
