### ISSUE TITLE
Release Schedule

### ISSUE THREAD

**Issue by JasonBristol** [suresttexas00/minecraft-wrapper#80]
Just to be clear since I know there has been some confusion, below is our current release schedule:

- [x] Staged Release 1 - Stable release of high priority bug fixes and optimizations
- [x] Code Cleanup & Refactor - Refactor of existing code base and code cleanup
- [x] Proxy Rewrite - Full proxy rewrite
- [ ] Feature Pack 1 - First set of added features
- [ ] Staged Release 2 - Stable release of features, bug fixes, and optimizations
- [ ] Feature Pack 2?

Let me know of any errors so I can adjust this for reference

**Comment by suresttexas00** [comment]
Yep...

**Comment by suresttexas00** [comment]
As we have moved back to Ben's branch, I am closing this.  The goal is now to simply fix all known bugs/issues, including why the new split module proxy performs so badly (LAGS badly), and then create a first release candidate to replace the current "master" branch.
