### ISSUE TITLE
Origin of core.nbt.py?

### ISSUE THREAD

**Issue by suresttexas00** [suresttexas00/minecraft-wrapper#88]
There are a number or errors (unresolved references) in this code.
  
~~One example that prevented minecraft.py from getting the worldspawnpoint()~~ 
~~is this in line 524 of nbt.py:~~

~~self.id is not defined.~~  

line 93ff
```
    # Parsers and Generators
    def _parse_buffer(self, buffer):
        # Note: buffer.read() may raise an IOError, for example if buffer is a
        # corrupt gzip.GzipFile
        self.value = self.fmt.unpack(buffer.read(self.fmt.size))[0]

    def _render_buffer(self, buffer):
        buffer.write(self.fmt.pack(self.value))
```
`fmt`is not defined.

**Comment by suresttexas00** [comment]
also line 93ff
```
    # Parsers and Generators
    def _parse_buffer(self, buffer):
        # Note: buffer.read() may raise an IOError, for example if buffer is a
        # corrupt gzip.GzipFile
        self.value = self.fmt.unpack(buffer.read(self.fmt.size))[0]

    def _render_buffer(self, buffer):
        buffer.write(self.fmt.pack(self.value))
```
`fmt`is not defined.

**Comment by suresttexas00** [comment]
id used again line 601 - same unresolved error:
`        TAG_Byte(self.id)._render_buffer(self.file)`

**Comment by suresttexas00** [comment]
There are three unused imports:
```import zlib  # unused
import os  # unused
import io  # unused```

I added this one to resolve exception MalformedFileError later in code:
`from exceptions import MalformedFileError`

**Comment by JasonBristol** [comment]
`id` should be changed to `tid`

Not sure why that `fmt` error is there, `TAG` has no `fmt` property until later

**Comment by suresttexas00** [comment]
the past commit fixed the problem with world NBT parsing that was giving my plugin errors. I will remove the milestone again and modify the labels.

**Comment by suresttexas00** [comment]
All yours for a while!  I will be concentrating on my own plugins and some work-and-home-related stuff. for a the time being.

**Comment by suresttexas00** [comment]
One more PR, though :( ...

**Comment by JasonBristol** [comment]
So it looks like `fmt` has always been referenced there. It is kind of unsafe because it assumes the `TAG` class is ALWAYS going to be subclassed and extended. All other classes initialize a `fmt` which allows those functions to work.

Fortunately, I don't think this will ever crop up again for us. The real issue was the missing `id` -> `tid` update which may have been causing the object to become null, and therefore not have a `fmt`.

Closing this for now unless it ever comes up again
