### ISSUE TITLE
Revisit Function Names

### ISSUE THREAD

**Issue by JasonBristol** [suresttexas00/minecraft-wrapper#97]
Various function names are unclear as to their intention and many are not camelCased (appears to be the overriding style, we can use PEP-8's suggestion for all lowercase with underscores as well, i.e. `check_for_updates`).

***e.g. - checkForUpdates vs checkForUpdate***
If I am trying to call these functions I have no idea what they are doing based on their name, I would have to look at their code.

This is extremely inefficient from a development perspective.

Perhaps these should be combined or renamed

```python
def checkForUpdates(self):
    if not IMPORT_REQUESTS:
        self.log.error("Can't automatically check for new Wrapper.py versions because you do not have the requests module installed!")
        return
    while not self.halt:
        time.sleep(3600)
        self.checkForUpdate(True)

def checkForUpdate(self, auto):
    self.log.info("Checking for new builds...")
    update = self.checkForNewUpdate()
    if update:
        version, build, repotype = update
        if repotype == "dev":
            if auto and not self.config["General"]["auto-update-dev-build"]:
                self.log.info("New Wrapper.py development build #%d available for download! (currently on #%d)", build, globals.__build__)
                self.log.info("Because you are running a development build, you must manually update Wrapper.py. To update Wrapper.py manually, please type /update-wrapper.")
            else:
                self.log.info("New Wrapper.py development build #%d available! Updating... (currently on #%d)", build, globals.__build__)
            self.performUpdate(version, build, repotype)
        else:
            self.log.info("New Wrapper.py stable %s available! Updating... (currently on %s)", \
                ".".join([str(_) for _ in version]), globals.__version__)
            self.performUpdate(version, build, repotype)
    else:
        self.log.info("No new versions available.")
```

This is a cleanup activity

**Comment by suresttexas00** [comment]
what is the accepted use of camelCase...?  When should it be and not be used?

**Comment by JasonBristol** [comment]
camelCase is typically used for all variables and functions. All classes use TitleCase, and all constants use UPPERCASE, note that a variable or function name that is one word like `start` is still considered camelCase

**Comment by suresttexas00** [comment]
I was wondering because one of the pep-8 checks complained about camelCase names in parts of wrapper.
Should we use this as our standard:
https://www.python.org/dev/peps/pep-0008/#naming-conventions
?

**Comment by JasonBristol** [comment]
Will begin this one for patch 8 since it is low hanging fruit to help wrap up code refactor & cleanup.

Marking this for personal reference:

__Checked Files:__

***api***
- [ ] base.py
- [ ] entity.py
- [ ] minecraft.py
- [ ] permissions.py
- [ ] player.py
- [ ] world.py
***core***
- [ ] backups.py
- [ ] commands.py
- [ ] config.py
- [ ] events.py
- [ ] exceptions.py
- [ ] globals.py
- [ ] irc.py
- [ ] items.py
- [ ] mcserver.py
- [ ] mcuuid.py
- [ ] nbt.py
- [ ] permissions.py
- [ ] plugins.py
- [ ] scripts.py
- [ ] storage.py
- [ ] wrapper.py
***management***
- [ ] web.py
- [ ] dashboard.py
***proxy***
- [ ] base.py
- [ ] client.py
- [ ] mcpacket.py
- [ ] packet.py
- [ ] server.py
***utils***
- [ ] helpers.py
- [ ] encryption.py
- [ ] log.py
- [ ] six.py
- [ ] termcolors.py
- [ ] version.py

**Comment by JasonBristol** [comment]
Note, these adjustments __will__ break custom plugins. Please make sure to review your plugins post patch 8

**Comment by suresttexas00** [comment]
Hmmm... see my post on #98   Not quite sure what we would define as a custom plugin due to the poor documentation of wrapper.

**Comment by suresttexas00** [comment]
Breaking plugins is an area that needs to be treaded upon lightly.

**Comment by JasonBristol** [comment]
Custom plugins are defined as plugins that don't ship with our wrapper build, i.e. does not exist in `example-plugins`. 

I agree to some extend regarding breaking plugins, but it is impossible to avoid this, users may create and leverage plugins in ways that are deemed `unsafe`, i.e. they invoke or reference deep areas of the wrapper that they maybe shouldn't integrate with directly. If you ask me, our plugin implementation should expose a `PluginAdapter` class of some sort that is the direct interface that __all__ plugins must interface with. This way when we make major changes, their references are abstracted enough not to break.

As of right now we don't have this in place, expect potential breaking changes to all plugins as wrapper goes through refactor & cleanup.

**Comment by suresttexas00** [comment]
well, NO (working or useful) plugins ship with wrapper!!  D: .. except for a couple C0ugar wrote (teleports home and bookmarks).  I agree so long as you are not going to muddle with the formal api.

Honestly, beyond the api, most plugins (even mine!) don't dig that deep.  I have some that use client.send() for fake packets, like blocks and particles, etc, but that is mostly it.. 

there are some others that did into some UUID operations which (understandably) have to be adjusted.. but I knew that at the outset.

what you are talking about with PluginAdapter is what Ben intended api to be used for .

**Comment by JasonBristol** [comment]
Your right, none do right now, but we need to be forward thinking when it comes to these changes. Right now this might not apply, your plugins might not do this, mine actually have to in order to get the value I need from wrapper. This is why we are here building it the right way so we won't have to. I might not be the only one.

I guess we would need to define what our API is. For me, and part of my suggestion, assumes that the API is our interface into the wrapper itself. This can be leveraged by plugins yes, but these API methods may change as ***wrapper*** changes. What we need is another layer of abstraction for plugins themselves. An adapter would interface with our API in a ***safe*** way that would not break players plugins.

I will illustrate:

```python
from api.base import API

self.api = API(....)

self.api.callEvent(...) # if we modify callEvent, this breaks

```

versus

```python
from api.adapters import PluginAdapter

self.adapter = PluginAdapter(....)

self.adapter.callEvent(...) # This won't break, see below
```

from ***PluginAdapter*** class

```python
from api.base import API

self.api = API(...)

def callEvent(...):
    # When changes to the API occur, changes to the adapter ship with it. This method will never break
    self.api.callEvent(...) 

```

**Comment by suresttexas00** [comment]
We already have api as the abstraction layer.. why would we need to create an abstraction for an abstraction?  Why change callEvent() in the api?  maybe you can use a real event to clear this up for me..?

For instance, why change player.getGamemode() to player.findgamemode() ???

**Comment by JasonBristol** [comment]
***api.base***

```python
# -*- coding: utf-8 -*-

import time

import core.exceptions as exceptions

from minecraft import Minecraft
from core.storage import Storage

""" api.py contains the majority of code for the plugin API. """

class API:
    """ 
    The API class contains methods for basic plugin functionality, such as handling events, registering commands, and more. 
    Most methods aren't related to gameplay, aside from commands and events, but for core stuff. See the Minecraft class (accessible at self.api.minecraft) for more gameplay-related methods. 
    """
    statusEffects = {
        "speed": 1,
        "slowness": 2,
        "haste": 3,
        "mining_fatigue": 4,
        "strength": 5,
        "instant_health": 6,
        "instant_damage": 7,
        "jump_boost": 8,
        "nausea": 9,
        "regeneration": 10,
        "resistance": 11,
        "fire_resistance": 12,
        "water_breathing": 13,
        "invisibility": 14,
        "blindness": 15,
        "night_vision": 16,
        "hunger": 17,
        "weakness": 18,
        "poison": 19,
        "wither": 20,
        "health_boost": 21,
        "absorption": 22,
        "saturation": 23
    }
    colorCodes = {
        "0": "black",
        "1": "dark_blue",
        "2": "dark_green",
        "3": "dark_aqua",
        "4": "dark_red",
        "5": "dark_purple",
        "6": "gold",
        "7": "gray",
        "8": "dark_gray",
        "9": "blue",
        "a": "green",
        "b": "aqua",
        "c": "red",
        "d": "light_purple",
        "e": "yellow",
        "f": "white",
        "r": "\xc2\xa7r",
        "k": "\xc2\xa7k",  # obfuscated
        "l": "\xc2\xa7l",  # bold
        "m": "\xc2\xa7m",  # strikethrough
        "n": "\xc2\xa7n",  # underline
        "o": "\xc2\xa7o",  # italic,
    }

    def __init__(self, wrapper, name="", aid=None, internal=False):
        self.wrapper = wrapper
        self.name = name
        self.minecraft = Minecraft(wrapper)
        self.server = wrapper.server
        self.internal = internal
        if aid is None:
            self.id = name
        else:
            self.id = aid

    def registerCommand(self, command, callback, permission=None):
        """ This registers a command that, when executed in Minecraft, will execute callback(player, args). 
        permission is an optional attribute if you want your command to only be executable if the player has a specified permission node.
        """
        commands = []
        if type(command) in (tuple, list):
            for i in command:
                commands.append(i)
        else:
            commands = [command]
        for name in commands:
            if not self.internal:
                self.wrapper.log.debug("[%s] Registered command '%s'", self.name, name)
            if self.id not in self.wrapper.commands:
                self.wrapper.commands[self.id] = {}
            self.wrapper.commands[self.id][name] = {"callback": callback, "permission": permission}

    def registerEvent(self, eventType, callback):
        """ Register an event and a callback. See [doc link needed here] for a list of events. callback(payload) when an event occurs, and the contents of payload varies between events."""
        if not self.internal:
            self.wrapper.log.debug("[%s] Registered event '%s'", self.name, eventType)
        if self.id not in self.wrapper.events:
            self.wrapper.events[self.id] = {}
        self.wrapper.events[self.id][eventType] = callback

    def registerPermission(self, permission=None, value=False):
        """ Used to set a default for a specific permission node. 
        Note: You do not need to run this function unless you want certain permission nodes to be granted by default. 
        i.e. `essentials.list` should be on by default, so players can run /list without having any permissions."""
        if not self.internal:
            self.wrapper.log.debug("[%s] Registered permission '%s' with default value: %s", self.name, permission, value)
        if self.id not in self.wrapper.permission:
            self.wrapper.permission[self.id] = {}
        self.wrapper.permission[self.id][permission] = value

    def registerHelp(self, groupName, summary, commands):
        """ Used to create a help group for the /help command. groupName is the name you'll see in the list when you run /help, and summary is the text that you'll see next to it.
        The 'commands' argument is passed in the following format: 
        [("/i <TileName>[:Data] [Count]", "Gives the player the requested item and puts it directly in their inventory.", "essentials.give"), ("/")]
        """
        if not self.internal:
            self.wrapper.log.debug("[%s] Registered help group '%s' with %d commands", self.name, groupName, len(commands))
        if self.id not in self.wrapper.help:
            self.wrapper.help[self.id] = {}
        self.wrapper.help[self.id][groupName] = (summary, commands)

    def blockForEvent(self, eventType):
        """ Blocks until the specified event is called. """
        sock = []
        self.wrapper.listeners.append(sock)
        while True:
            for event in sock:
                if event["event"] == eventType:
                    payload = event["payload"][:]
                    self.wrapper.listeners.remove(sock)
                    return payload
                else:
                    sock.remove(event)
            time.sleep(0.05)

    def callEvent(self, event, payload):
        """ Invokes the specific event. Payload is extra information relating to the event. Errors may occur if you don't specify the right payload information. """
        return self.wrapper.callEvent(event, payload)

    def getPluginContext(self, pid):
        """ Returns the content of another plugin with the specified ID. 
        i.e. api.getPluginContext(\"com.benbaptist.plugins.essentials\")"""
        if pid in self.wrapper.plugins:
            return self.wrapper.plugins[pid]["main"]
        else:
            raise exceptions.NonExistentPlugin("Plugin %s does not exist!" % pid)

    def getStorage(self, name, world=False):
        """ Return a storage object for storing configurations, player data, and any other data your plugin will need to remember across reboots.
        Setting world=True will store the data inside the current world folder, for world-specific data.  
        """
        if not world:
            return Storage(name, False, root=".wrapper-data/plugins/%s" % self.id)
        else:
            return Storage(name, True, root="%s/plugins/%s" % (self.minecraft.getWorldName(), self.id))

```

Nothing about this module is abstracted. Each function is actually doing real work to return the result.

Assume we change the signature of the storage class:
```Storage(name, True, root="%s/plugins/%s" % (self.minecraft.getWorldName(), self.id))``` ___breaks___!

Assume we change the format of our events:
```self.wrapper.events[self.id][eventType] = callback``` ___breaks___!

Assume we change the format of our permissions:
```self.wrapper.permission[self.id][permission] = value``` ___breaks___!

Need any more?

This is just from our base class, this does not even touch on our other API classes. Each of which perform actual operations that may change as we improve the wrapper, every single plugin using these may receive a different output from these functions, may find the function has been renamed, etc.

What I suggest is considered safe because it has the power to ensure that no matter how the API changes, plugins will continue to function.

**Comment by suresttexas00** [comment]
that's because you are not supposed to call these functions in that manner.  Every one of these should simply be self.api.wrapper.getPluginContext, self.api.registerCommand("filter", self._filter, None), etc...

**Comment by suresttexas00** [comment]
samples:
```
class Main:
    def __init__(self, api, log):
        self.api = api
        self.minecraft = api.minecraft
        self.log = log
        self.claimsdata = api.getPluginContext("com.suresttexas00.plugins.vanillaclaims")
        self.globalset = api.getPluginContext("com.suresttexas00.plugins.global")
```
```
    def onEnable(self):

        self.api.registerHelp("Commands", "General commands on the server", [
            ("/home <player> <visit|set>", "Set a new player's home or TP to an existing home.", ...
```

The functions don't have wrappers, so they DO do work, but the call to them is unchanged.

**Comment by suresttexas00** [comment]
And accessing permissions values outside of the api is a no-no anyway:
```self.wrapper.permission[self.id][permission] = value```

**Comment by JasonBristol** [comment]
I don't understand how your example prevents the scenarios I listed, assume I changed the wrapper.plugins definition which would impact ```return self.wrapper.plugins[pid]["main"]```

You will either no longer receive any value from calling ```getPluginContext```
Or you will receive an object that may no longer have the same signature, so your parsing of `self.claimsdata` is no longer parsable.

**Comment by suresttexas00** [comment]
ok, lets talk about a specific function.. lets use that ```self.claimsdata = api.getPluginContext("com.suresttexas00.plugins.vanillaclaims")```

lets say I set self.claimsdata = {"name": "Surest", "property": "0,0,0"}

how will it be broken? 

I'm not sure what you are referring to when you say a "signature"..?  If you are returning something other than the plugin referenced by the function (my vanillaclaims storage object that I defined in the vanillaclaims plugin),  then you are intentionally breaking the api and just having another function wrap it will not help:

```
from api.adapters import PluginAdapter

self.adapter = PluginAdapter(....)

self.adapter.getPluginContext_new(...) # This won't break, see below
```

```
from api.base import API

self.api = API(...)

def getPluginContext_new(...):
    # When changes to the API occur, changes to the adapter ship with it.
    # This method will never break
    self.api.getPluginContext_old(...)   # still calling some event you broke by returning something other than my plugin
```

**Comment by suresttexas00** [comment]
I guess this is what I am getting out of this; and maybe that's not what you mean:

```
myplugin:
x = self.api.functionx(myargs)
```

api
```
def functionx(args):
    """does a whole bunch of stuff.. how it does it and the internal structures change or get optimized/refactored """
return some value
```

pluginadapter
```
def functionX(args):
    return functionx
```

**Comment by JasonBristol** [comment]
```python
from api.adapters import PluginAdapter

self.adapter = PluginAdapter(....)

self.adapter.getPluginContext_new(...) # This won't break, see below
from api.base import API

self.api = API(...)

def getPluginContext_new(...):
    # When changes to the API occur, changes to the adapter ship with it.
    # This method will never break
    #self.api.getPluginContext_old(...)   # I can't change your plugin when I make breaking changes, but I can change the adapter shipped with the new version. Your plugin will not break
    self.api.getPluginContext_new(...)
```
<hr>
> lets say I set self.claimsdata = {"name": "Surest", "property": "0,0,0"}
how will it be broken?

Your setting `self.claimsdata` explicitly, it can't break the way we are talking...

Your `functionX` example is correcy, that is what I am saying, except your call in your plugin would be this instead:

```x = self.pluginadapter.functionx(myargs)```

**Comment by suresttexas00** [comment]
How else would you set the claimsdata?  claimsdata is just a json storage object, whose format is defined by the claimsdata plugin... And I am still confused why a pluginadapter wrapper is needed over api... well anyway, it really is a moot point, nothing you just did changes the api except for:

processColorCodesOld to processOldColorCodes (which I doubt anyone uses)
*__*track*__* to track-  which is not a part of the api interface (just a function that updates the players login time on the server)

All of your changes are internal and do not affect the calling user plugin, for example, in player.py:
![image](https://cloud.githubusercontent.com/assets/10001762/14626288/1dfd32a8-05b8-11e6-8e74-78faf36a4770.png)
It is never intended to call "wrapper.fuctions"  If a plugin needs a UUID, that should go via the api.

seems like this whole pluginadapter is just another way of doing what you criticize here:
![image](https://cloud.githubusercontent.com/assets/10001762/14626365/aff784ba-05b8-11e6-9104-e1a91044c06c.png)

**Comment by suresttexas00** [comment]
As I said, we are not supposed to use things like wrapper.thisInternal and wrapper.thatInternal?  If that is the case, that is certainly an improper abuse of the intent.  Sometimes it is done.. here is my own example of abuse:

```
class Main:
    def __init__(self, api, log):
        self.api = api
        self.minecraft = api.minecraft
        self.log = log
        self.wrapper = self.api.wrapper  # used by wrapper halts section

        self.timer = 0
        # Wrapper halts and server saves
        self.do_wrapperHalts = True

...

    def onSecond(self, payload):
        self.timer += 1
...

        if self.do_wrapperHalts:
...
            if self.timer % self.restartwrapper_freq == 0:
                self.wrapper.shutdown()
```

These sorts of plugin calls are at the writers risk... but most legit functions are in the  api.base, api.minecraft and api.player sections... I believe departing from these modules (which are documented in ben's reference "get an idea of" api or the wiki I based off of it...) is what sets the criteria for a plugin to be called "custom" and subject to a lack of support (Ben has criticized my use of non-standard wrapper features as a reason to disregard many of wrappers serious bugs in the past).

**Comment by suresttexas00** [comment]
had a little typo last night; it was supposed to read:  

 __"ok, lets talk about a specific function.. lets use that `self.claimsdata = api.getPluginContext("com.suresttexas00.plugins.vanillaclaims")`__  
__lets say I set `self.claimsdata`*.claims*` = {"name": "Surest", "property": "0,0,0"}"`__ 

I am accessing the json storage object in another plugin with this method.

I think the difference in our view points on this is that I am not viewing the entire wrapper as the api, and only the api modules in the api folder as the api, which is Ben's current method.  If you are really wanting the include all of wrapper's modules, you should build that abstraction later.  My opinion is that you should make that a part of api.. perhaps add an "abstractions" module there...

**Comment by JasonBristol** [comment]
Our api would need to be refactored to bring it to the level of what I am suggesting with a plugin adapter. That is fine, I will spin up a milestone for it

btw [signature](https://www.python.org/dev/peps/pep-0362/)
