### ISSUE TITLE
Build a Wrapper Test-Driven Module

### ISSUE THREAD

**Issue by suresttexas00** [suresttexas00/minecraft-wrapper#98]
We need a standard piece of code (a plugin?) that will test every aspect of the API.  This is pretty new to me.  I'm not sure what the best way to write this would be.

I have listed the basic list from the formal API (master branch) here in this start of a plugin.  Of course, there are "sub functions" that extend under the api.. for instance, the api has getPlayer and getClient methods, etc, which expose some private wrapper functionality that is not currently documented in the api docs/wiki.  For instance, getClient.send() to send packets.  Those parts we deem as a legit part of the api should probably be public functions and those parts that are not.. should be *_*private.  This may mean some more refactoring.

Besides the lower level stuff, we need to create something that will, for a start, test these methods and properties are working:
```python
NAME = "wrapperTest"
AUTHOR = "SurestTexas00"
ID = "com.suresttexas00.plugins.wrappertest"
VERSION = (0, 1)
SUMMARY = "test module"
WEBSITE = ""
DESCRIPTION = "this module is for testing of the wrapper functionality.  Goal is to test all supported aspects of" \
              "the wrapper api and all in game functions."
DEPENDENCIES = ["testlist.py"]
DISABLED = False


class Main:
    def __init__(self, api, log):
        self.api = api
        self.minecraft = api.minecraft
        self.log = log
        self.log.warn("starting tests (import of wrappertest class Main)")
        self.log.error("Errors appear like this...")
        try:
            self.testcode = self.api.getPluginContext("com.suresttexas00.plugins.testlist")
            self.log.warn("import of another plugin context succeeded")
        except Exception as e:
            self.log.error("import of plugin context failed: %s" % e)
        self.testingcode = self.testcode.tests


    def onEnable(self):
        """Test Items"""

        # I don't think many of these methods actually ever worked because the world data is not parsed.
        # getEntitybyEID, Setblock, Fill, and Replace might work
        """ World tests Api.world.World
        """
        # getBlock(self, pos):
        # setChunk(self, x, z, chunk):
        # getEntityByEID(self, eid):  # TODO test elsewhere (where we know an entity might exist)
        # setBlock(self, x, y, z, tilename, damage=0, mode="replace", data={}):
        # fill(self, position1, position2, tilename, damage=0, mode="destroy", data={}):
        # replace(self, position1, position2, tilename1, damage1, tilename2, damage2=0):

        # unused, I believe
        """ World tests Api.world.Chunk
        """
        # getBlock(self, x, y, z):

        """class Minecraft:"""
        #   (wrapper)
        #    Accessed using ===> self.api.minecraft
        # isServerStarted(self):
        # getAllPlayers(self):
        # console(self, string):
        # setBlock(self, x, y, z, tileName, dataValue=0, oldBlockHandling="replace", dataTag={}):
        # giveStatusEffect(self, player, effect, duration=30, amplifier=30):
        # summonEntity(self, entity, x=0, y=0, z=0, dataTag={}):
        # message(self, destination="", json_message={}):
        # broadcast(self, message="", irc=False):
        # teleportAllEntities(self, entity, x, y, z):
        # lookupUUID(self, uuid):
        # getPlayers(self): # returns a list of players
        # getLevelInfo(self, worldName=False):
        # getSpawnPoint(self):
        # getTime(self):
        # getServer(self):
        # getWorld(self):
        # getWorldName(self):
        # getPlayer(self, username=""):

        """class Player:"""
        # accessed by getPlayer(self, username=""):  ====> self.api.minecraft.getplayer("username")

        '''  attributes:
        self.wrapper = wrapper
		self.server = wrapper.server
		self.permissions = wrapper.permissions
		self.name = username
		self.username = self.name # just an alias - same variable
		self.loggedIn = time.time()
		self.abort = False
		self.uuid = self.wrapper.getUUID(username)
		self.data = storage.Storage(self.uuid, root="wrapper-data/players")
		self.data["firstLoggedIn"] = (time.time(), time.tzname)
		self.data["logins"] = {}'''

        # console(self, string): Run a command in the Minecraft server's console.
        # execute(self, string): string (command) is sent straight to the vanilla server
        # say(self, string):
        # getClient(self):
        # processColorCodesOld(self, message): # Not sure if this is used anymore. Might delete.
        # getPosition(self):
        # getGamemode(self):
        # getDimension(self):
        # setGamemode(self, gm=0):
        # setResourcePack(self, url):
        # isOp(self):
        # message(self, message=""):
        # actionMessage(self, message=""):
        # setVisualXP(self, progress, level, total):
        # openWindow(self, type, title, slots):
        # setPlayerFlying(self, fly): # UNFINISHED FUNCTION
        # setBlock(self, position): # Unfinished function, will be used to make phantom blocks visible ONLY to the client
        # getItemInSlot(self, slot):
        # getHeldItem(self):
        # hasPermission(self, node):
        # hasGroup(self, group):
        # getGroups(self):
        # getFirstLogin(self):
        # connect(self, ip, address):


        """class Entity:"""

        # moveRelative(self, position):
        # teleport(self, position):

        pass


    def onDisable(self):
        pass
```

So how to implement?  Do we just write a code that try-excepts all these methods... Do we just run it all and when something errors out, we fix that error, run it again to get to the second broken item, etc?

**Comment by JasonBristol** [comment]
Absolutely agree, this is called test driven development. It is relatively new, but automated test cases go a long way in terms of rapid development. I think the plugin approach is sound, assuming we can hit all aspects. If a plugin ends up limiting us too much, we can leverage a python script to basically import our entire wrapper package and go to town.

We would basically have a series of functions that each test a test-case. Each test case is executed in a try-catch and on failure throws an exception. We would then have a runner function that spins through each test-case and basically prints or records ones that throw an exception. It would continue onto the next test-case regardless of success/failure.

Output would be something similar to this:

```
[21:29:13] [Wrapper Tests/INFO]: Test 1 - getUsernameByUUID(<class - Wrapper>, abcd-efg-hijklmnop): Result - SUCCESS
...
```

We would print out the function call and the parameters passed into it, as well as its result. We can kill two birds with one stone by leveraging `log.py` for logging, if `log.py` was busted we would know instantly. Any additional tests against `log.py` would be implemented in the test-cases.

The trickiest part is isolating what really needs to be tested. What you have posted as an example would take a long way, be insanely difficult to simulate use cases for some functions, and may be more work than is needed. Ultimately we will be wanting to test the ***big** stuff like proxy communication and packet parsing, etc, basically test-cases that simulate real use-cases.

Tests driven this way are to make sure that wrapper is minimally stable, meaning that it is not broken. These tests won't be to find minute bugs throughout the code, we will discover these as they appear, but we certainly don't want to push a busted build out which this activity is designed to avoid.

**Comment by suresttexas00** [comment]
It is exactly those small bugs that I __do__ want to find quickly (like the last getspawnpoint() example that was caused by a bugged nbt parsing routine.. a simple typo.  Finding these things is too hit-or-miss right now... I load the new wrapper up, start the server, logon and try random functions from my plugins commands...  but it is hard to test everything properly. 

The big stuff generally, like the log coding, is self evident and "tests" itself..

**Comment by suresttexas00** [comment]
So much code is going un-tested while we may be unknowingly introducing more and more errors.

**Comment by suresttexas00** [comment]
The items listed above are "standard" api items that would definitely be a minimum standard for testing.  So is there some sort of looping construct I could use or do I just write a big sequence of try-excepts?

**Comment by suresttexas00** [comment]
some of these things build on one another.. if you run getSpawnPoint(), you then have a valid set of (server loaded) coordinates to start testing fill, setblock, etc... then once a player logs on, proceed to the other tests

**Comment by suresttexas00** [comment]
I think this is going to be more simple and straightforward to simply have the items tested by the plugin in-game.  Since the end goal of the code is that it will run error free for a valid build, the fact that it does not catch every error at first run may not be a large issue.

I will start by just testing those items listed, which represent the formal api as published or listed in the api code base.

**Comment by JasonBristol** [comment]
I have serious doubts, there is no such test suite available that can find bugs of the nature you describe. Your goal is too broad for a concise test case, consider reconsidering based on my suggestion.

**Comment by JasonBristol** [comment]
I we had a tool to run through our entire code and find every bug we would all be paid significantly less and debugging would be obsolete.

Unfortunately, we have no capability to find these minor bugs (typos etc) unless they are raised at a high level. The only thing we can and ***should*** do is ensure that the wrapper has no critical issues and can run i.e. doesn't throw an exception etc (This is why error handling was so important). Any bugs that cause issues like that would be caught, so assuming getSpawnPoint() was actually throwing an exception when it couldn't do its thing, we would pick it up in a test suite.

The issue gets even more difficult if we are talking packets, assuming the payload is incorrect, the jar may not throw any exception, and if it does it is not exposed to the wrapper, we have no visibility into jar errors (think malformed json exceptions).

**Comment by suresttexas00** [comment]
I find most errors by going on an manually typing '/van', '/home', etc.. and all these fail because of some specific part of the api being broken.  simply having something like:

```
    x = getspawnpoint()
    print x (or log it, whatever)  goes a long way to do an easy check for functionality.
```

just automating the gruntwork me and my staff do everytime I update wrapper...
identify what DOES NOT work... then start debugging it..

If it all works.. unit passed!

**Comment by JasonBristol** [comment]
I don't think we are disagreeing, I think you misunderstood what I am saying. If you can run `/van` and it works, thats an individual test case, but if your trying to run every since function in every single module, you may not have any luck since you would have to simulate every interaction possible

Also keep in mine that building a test case around ***your*** custom plugins in not valid as a ***wrapper*** test case. You would probably want to extend the `tests.base` module we would build and add your custom test cases. This can be done easily

**Comment by suresttexas00** [comment]
The /van thing is testing a few key areas in the api:
-getClient
-getCleint.send()
-that the player.uuid is suitable for use in the packet sending methods called in client.send for sending the packet type_ "uuid".

It is actually a wrapper test case too.  The test code I am proposing would do the same steps, without me having to log in and type /van.. I would not even have to have a plugin installed..  That is just one sample of how I test it with my own plugins... but using MY plugins to decide if code is stable is something I definitely want to get away from.

**Comment by JasonBristol** [comment]
That is fine, again I am refering to your first post with the psuedo code you posted. You asked for help identifying how to go about this, I am disagreeing with what you have outlined in your original post.

We cannot, I mean this, __cannot__ test every possible variable, every single function, and every single permutation of an interaction. What we can do is what I have described and what you are alluding to with `/van` -- individual test cases being executing against very specific sets of criteria with a very specific expected result. If you are looking for a magic script to ensure that wrapper is 100% bug free I am just making it clear that is not possible.

**Comment by suresttexas00** [comment]
Yes, I believe a "test drive" is a good analogy here... you won't find every issue or problem with a car in a short test drive, but if done on a nice sample of roadway, you can get a good idea of how good the vehicle handles, how the controls feel, etc, etc.. enough to say what you do and do not like about it.

**Comment by suresttexas00** [comment]
Probably not needed in the manner I envisioned.  And certainly not practical.
